using System;

namespace VibeXASR.Windows.Refine;

/// <summary>Built-in cloud LLM provider catalog — faithful 1:1 port of macOS CloudCatalog.swift
/// (23 OpenAI-compatible providers + model presets; provider keys / marks / model ids verbatim).
/// Generated from the macOS source; do not hand-edit model lists.</summary>
internal static class CloudCatalog
{
    public static readonly LlmProvider[] Providers =
    {
        new() { Key = "openai", Label = "OpenAI", Mark = "AI", Cls = "oa", Desc = "OpenAI",
                BaseUrl = "https://api.openai.com/v1", KeyHint = "sk-...", ModelLabel = "模型", DefaultModel = "gpt-5.4-mini",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("gpt-5.5", "GPT-5.5", ""),
                    new LlmModel("gpt-5.5-pro", "GPT-5.5 pro", ""),
                    new LlmModel("gpt-5.4", "GPT-5.4", ""),
                    new LlmModel("gpt-5.4-pro", "GPT-5.4 pro", ""),
                    new LlmModel("gpt-5.4-mini", "GPT-5.4 mini", ""),
                    new LlmModel("gpt-5.4-nano", "GPT-5.4 nano", ""),
                    new LlmModel("gpt-5.3-chat-latest", "GPT-5.3 Chat", ""),
                    new LlmModel("gpt-5.2", "GPT-5.2", ""),
                    new LlmModel("gpt-5.2-pro", "GPT-5.2 pro", ""),
                    new LlmModel("gpt-5.2-chat-latest", "GPT-5.2 Chat", ""),
                    new LlmModel("gpt-5.1", "GPT-5.1", ""),
                    new LlmModel("gpt-5.1-chat-latest", "GPT-5.1 Chat", ""),
                    new LlmModel("gpt-5", "GPT-5", ""),
                    new LlmModel("gpt-5-pro", "GPT-5 pro", ""),
                    new LlmModel("gpt-5-mini", "GPT-5 mini", ""),
                    new LlmModel("gpt-5-nano", "GPT-5 nano", ""),
                    new LlmModel("gpt-5-chat-latest", "GPT-5 Chat", ""),
                    new LlmModel("o4-mini", "o4-mini", ""),
                    new LlmModel("o3-pro", "o3-pro", ""),
                    new LlmModel("o3", "o3", ""),
                    new LlmModel("o3-mini", "o3-mini", ""),
                    new LlmModel("gpt-4.1", "GPT-4.1", ""),
                    new LlmModel("gpt-4.1-mini", "GPT-4.1 mini", ""),
                    new LlmModel("gpt-4.1-nano", "GPT-4.1 nano", ""),
                    new LlmModel("chatgpt-4o-latest", "ChatGPT-4o", ""),
                    new LlmModel("gpt-4o", "GPT-4o", ""),
                    new LlmModel("gpt-4o-mini", "GPT-4o mini", ""),
                    new LlmModel("gpt-4-turbo", "GPT-4 Turbo", ""),
                    new LlmModel("gpt-4", "GPT-4", ""),
                    new LlmModel("gpt-3.5-turbo", "GPT-3.5 Turbo", ""),
                } },
        new() { Key = "claude", Label = "Claude", Mark = "Cl", Cls = "claude", Desc = "Anthropic",
                BaseUrl = "https://api.anthropic.com", KeyHint = "sk-ant-...", ModelLabel = "模型", DefaultModel = "claude-sonnet-4-6",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("claude-opus-4-7", "Claude Opus 4.7", ""),
                    new LlmModel("claude-opus-4-6", "Claude Opus 4.6", ""),
                    new LlmModel("claude-opus-4-5-20251101", "Claude Opus 4.5", ""),
                    new LlmModel("claude-opus-4-1-20250805", "Claude Opus 4.1", ""),
                    new LlmModel("claude-sonnet-4-6", "Claude Sonnet 4.6", ""),
                    new LlmModel("claude-sonnet-4-5-20250929", "Claude Sonnet 4.5", ""),
                    new LlmModel("claude-haiku-4-5-20251001", "Claude Haiku 4.5", ""),
                    new LlmModel("claude-sonnet-4-20250514", "Claude Sonnet 4", ""),
                    new LlmModel("claude-opus-4-20250514", "Claude Opus 4", ""),
                    new LlmModel("claude-3-7-sonnet-20250219", "Claude Sonnet 3.7", ""),
                    new LlmModel("claude-3-5-sonnet-20241022", "Claude Sonnet 3.5", ""),
                    new LlmModel("claude-3-5-haiku-20241022", "Claude Haiku 3.5", ""),
                    new LlmModel("claude-3-haiku-20240307", "Claude Haiku 3", ""),
                } },
        new() { Key = "gemini", Label = "Google Gemini", Mark = "G", Cls = "gemini", Desc = "Google",
                BaseUrl = "https://generativelanguage.googleapis.com/v1beta", KeyHint = "AIza...", ModelLabel = "模型", DefaultModel = "gemini-3-flash-preview",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("gemini-3-flash-preview", "Gemini 3 Flash Preview", ""),
                    new LlmModel("gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview", ""),
                    new LlmModel("gemini-3.1-flash-lite-preview", "Gemini 3.1 Flash-Lite Preview", ""),
                    new LlmModel("gemini-pro-latest", "Gemini Pro Latest", ""),
                    new LlmModel("gemini-flash-latest", "Gemini Flash Latest", ""),
                    new LlmModel("gemini-flash-lite-latest", "Gemini Flash-Lite Latest", ""),
                    new LlmModel("gemini-2.5-pro", "Gemini 2.5 Pro", ""),
                    new LlmModel("gemini-2.5-flash", "Gemini 2.5 Flash", ""),
                    new LlmModel("gemini-2.5-flash-lite", "Gemini 2.5 Flash-Lite", ""),
                    new LlmModel("gemini-2.0-flash", "Gemini 2.0 Flash", ""),
                    new LlmModel("gemini-2.0-flash-lite", "Gemini 2.0 Flash-Lite", ""),
                } },
        new() { Key = "deepseek", Label = "DeepSeek", Mark = "DS", Cls = "deepseek", Desc = "DeepSeek",
                BaseUrl = "https://api.deepseek.com/v1", KeyHint = "API Key", ModelLabel = "模型", DefaultModel = "deepseek-v4-flash",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("deepseek-v4-flash", "DeepSeek V4 Flash", ""),
                    new LlmModel("deepseek-v4-pro", "DeepSeek V4 Pro", ""),
                    new LlmModel("deepseek-chat", "DeepSeek Chat (compatibility)", ""),
                    new LlmModel("deepseek-reasoner", "DeepSeek Reasoner (compatibility)", ""),
                } },
        new() { Key = "qwen", Label = "Qwen", Mark = "通", Cls = "qwen", Desc = "Alibaba Cloud DashScope",
                BaseUrl = "https://dashscope.aliyuncs.com/compatible-mode/v1", KeyHint = "sk-...", ModelLabel = "模型", DefaultModel = "qwen3.6-flash",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("qwen3.6-max-preview", "Qwen3.6 Max Preview", ""),
                    new LlmModel("qwen3.6-plus", "Qwen3.6 Plus", ""),
                    new LlmModel("qwen3.6-plus-2026-04-02", "Qwen3.6 Plus (2026-04-02)", ""),
                    new LlmModel("qwen3.6-flash", "Qwen3.6 Flash", ""),
                    new LlmModel("qwen3.6-flash-2026-04-16", "Qwen3.6 Flash (2026-04-16)", ""),
                    new LlmModel("qwen3.5-plus", "Qwen3.5 Plus", ""),
                    new LlmModel("qwen3.5-plus-2026-02-15", "Qwen3.5 Plus (2026-02-15)", ""),
                    new LlmModel("qwen3.5-flash", "Qwen3.5 Flash", ""),
                    new LlmModel("qwen3.5-flash-2026-02-23", "Qwen3.5 Flash (2026-02-23)", ""),
                    new LlmModel("qwen3.5-397b-a17b", "Qwen3.5 397B A17B", ""),
                    new LlmModel("qwen3.5-122b-a10b", "Qwen3.5 122B A10B", ""),
                    new LlmModel("qwen3.5-27b", "Qwen3.5 27B", ""),
                    new LlmModel("qwen3.5-35b-a3b", "Qwen3.5 35B A3B", ""),
                    new LlmModel("deepseek-v4-pro", "DeepSeek V4 Pro", ""),
                    new LlmModel("deepseek-v4-flash", "DeepSeek V4 Flash", ""),
                    new LlmModel("glm-5.1", "GLM-5.1", ""),
                    new LlmModel("kimi-k2.6", "Kimi K2.6", ""),
                    new LlmModel("kimi-k2.5", "Kimi K2.5", ""),
                    new LlmModel("MiniMax-M2.5", "MiniMax M2.5", ""),
                    new LlmModel("qwen3-max", "Qwen3 Max", ""),
                    new LlmModel("qwen3-max-2026-01-23", "Qwen3 Max (2026-01-23)", ""),
                    new LlmModel("qwen3-max-preview", "Qwen3 Max Preview", ""),
                    new LlmModel("qwen3-max-2025-09-23", "Qwen3 Max (2025-09-23)", ""),
                    new LlmModel("qwen3-coder-next", "Qwen3 Coder Next", ""),
                    new LlmModel("qwen3-coder-480b-a35b-instruct", "Qwen3 Coder 480B A35B Instruct", ""),
                    new LlmModel("qwen3-coder-30b-a3b-instruct", "Qwen3 Coder 30B A3B Instruct", ""),
                    new LlmModel("qwen3-coder-plus", "Qwen3 Coder Plus", ""),
                    new LlmModel("qwen3-coder-plus-2025-09-23", "Qwen3 Coder Plus (2025-09-23)", ""),
                    new LlmModel("qwen3-coder-plus-2025-07-22", "Qwen3 Coder Plus (2025-07-22)", ""),
                    new LlmModel("qwen3-coder-flash", "Qwen3 Coder Flash", ""),
                    new LlmModel("qwen3-coder-flash-2025-07-28", "Qwen3 Coder Flash (2025-07-28)", ""),
                    new LlmModel("qwen3-235b-a22b", "Qwen3 235B A22B", ""),
                    new LlmModel("qwen3-235b-a22b-thinking-2507", "Qwen3 235B A22B Thinking 2507", ""),
                    new LlmModel("qwen3-235b-a22b-instruct-2507", "Qwen3 235B A22B Instruct 2507", ""),
                    new LlmModel("qwen3-next-80b-a3b-thinking", "Qwen3 Next 80B A3B Thinking", ""),
                    new LlmModel("qwen3-next-80b-a3b-instruct", "Qwen3 Next 80B A3B Instruct", ""),
                    new LlmModel("qwen3-32b", "Qwen3 32B", ""),
                    new LlmModel("qwen3-30b-a3b", "Qwen3 30B A3B", ""),
                    new LlmModel("qwen3-14b", "Qwen3 14B", ""),
                    new LlmModel("qwen3-8b", "Qwen3 8B", ""),
                    new LlmModel("qwen3-4b", "Qwen3 4B", ""),
                    new LlmModel("qwen3-1.7b", "Qwen3 1.7B", ""),
                    new LlmModel("qwen3-0.6b", "Qwen3 0.6B", ""),
                    new LlmModel("qwen-plus", "Qwen Plus", ""),
                    new LlmModel("qwen-flash", "Qwen Flash", ""),
                    new LlmModel("qwen-plus-us", "Qwen Plus US", ""),
                    new LlmModel("qwen-flash-us", "Qwen Flash US", ""),
                    new LlmModel("qwen-turbo", "Qwen Turbo", ""),
                    new LlmModel("qwen-long", "Qwen Long", ""),
                    new LlmModel("qwq-plus", "QwQ Plus", ""),
                    new LlmModel("qwq-32b", "QwQ 32B", ""),
                    new LlmModel("qwen2.5-72b-instruct", "Qwen2.5 72B Instruct", ""),
                    new LlmModel("qwen2.5-32b-instruct", "Qwen2.5 32B Instruct", ""),
                    new LlmModel("qwen2.5-14b-instruct", "Qwen2.5 14B Instruct", ""),
                    new LlmModel("qwen2.5-7b-instruct", "Qwen2.5 7B Instruct", ""),
                    new LlmModel("qwen3-vl-plus", "Qwen3 VL Plus", ""),
                    new LlmModel("qwen3-vl-flash", "Qwen3 VL Flash", ""),
                    new LlmModel("qwen-vl-plus", "Qwen VL Plus", ""),
                    new LlmModel("qwen-vl-max", "Qwen VL Max", ""),
                    new LlmModel("qwen-vl-ocr", "Qwen VL OCR", ""),
                    new LlmModel("qwen3-omni-flash", "Qwen3 Omni Flash", ""),
                    new LlmModel("qwen-omni-turbo", "Qwen Omni Turbo", ""),
                } },
        new() { Key = "aliyun", Label = "Alibaba Cloud Bailian", Mark = "百", Cls = "aliyun", Desc = "Alibaba Cloud DashScope",
                BaseUrl = "https://dashscope.aliyuncs.com/compatible-mode/v1", KeyHint = "sk-...", ModelLabel = "模型", DefaultModel = "deepseek-v4-flash",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("deepseek-v4-pro", "DeepSeek V4 Pro", ""),
                    new LlmModel("deepseek-v4-flash", "DeepSeek V4 Flash", ""),
                    new LlmModel("deepseek-v3", "DeepSeek V3", ""),
                    new LlmModel("deepseek-r1", "DeepSeek R1", ""),
                } },
        new() { Key = "doubao", Label = "Doubao / Volcengine Ark", Mark = "豆", Cls = "doubao", Desc = "Volcano Ark",
                BaseUrl = "https://ark.cn-beijing.volces.com/api/v3", KeyHint = "ARK_API_KEY", ModelLabel = "模型", DefaultModel = "doubao-seed-1.6",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("doubao-seed-1.6", "Doubao Seed 1.6", ""),
                    new LlmModel("doubao-seed-1.6-thinking", "Doubao Seed 1.6 Thinking", ""),
                    new LlmModel("doubao-seed-1.6-flash", "Doubao Seed 1.6 Flash", ""),
                    new LlmModel("doubao-seed-code-preview-251028", "Doubao Seed Code Preview 251028", ""),
                    new LlmModel("doubao-1.5-thinking-pro", "Doubao 1.5 Thinking Pro", ""),
                    new LlmModel("doubao-1.5-pro-32k", "Doubao 1.5 Pro 32K", ""),
                    new LlmModel("doubao-1.5-lite-32k", "Doubao 1.5 Lite 32K", ""),
                    new LlmModel("doubao-lite-128k", "Doubao Lite 128K", ""),
                    new LlmModel("doubao-lite-32k", "Doubao Lite 32K", ""),
                    new LlmModel("doubao-1.5-vision-pro-32k", "Doubao 1.5 Vision Pro 32K", ""),
                } },
        new() { Key = "moonshot", Label = "Moonshot AI", Mark = "Ki", Cls = "moonshot", Desc = "Moonshot AI",
                BaseUrl = "https://api.moonshot.cn/v1", KeyHint = "sk-...", ModelLabel = "模型", DefaultModel = "kimi-k2.6",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("kimi-k2.6", "Kimi K2.6", ""),
                    new LlmModel("kimi-k2.5", "Kimi K2.5", ""),
                    new LlmModel("kimi-k2-thinking", "Kimi K2 Thinking", ""),
                    new LlmModel("kimi-k2-thinking-turbo", "Kimi K2 Thinking Turbo", ""),
                    new LlmModel("kimi-k2-turbo-preview", "Kimi K2 Turbo Preview", ""),
                    new LlmModel("kimi-k2-0905-preview", "Kimi K2 0905 Preview", ""),
                    new LlmModel("kimi-k2-0711-preview", "Kimi K2 0711 Preview", ""),
                    new LlmModel("moonshot-v1-8k", "Moonshot V1 8K", ""),
                    new LlmModel("moonshot-v1-32k", "Moonshot V1 32K", ""),
                    new LlmModel("moonshot-v1-128k", "Moonshot V1 128K", ""),
                    new LlmModel("moonshot-v1-8k-vision-preview", "Moonshot V1 8K Vision Preview", ""),
                    new LlmModel("moonshot-v1-32k-vision-preview", "Moonshot V1 32K Vision Preview", ""),
                    new LlmModel("moonshot-v1-128k-vision-preview", "Moonshot V1 128K Vision Preview", ""),
                } },
        new() { Key = "kimicodingplan", Label = "Kimi Coding Plan", Mark = "Ki", Cls = "kimicodingplan", Desc = "Kimi Coding Plan",
                BaseUrl = "https://api.moonshot.cn/anthropic", KeyHint = "sk-...", ModelLabel = "模型", DefaultModel = "kimi-k2.6",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("kimi-k2.6", "Kimi K2.6", ""),
                    new LlmModel("kimi-k2.5", "Kimi K2.5", ""),
                    new LlmModel("kimi-k2-thinking", "Kimi K2 Thinking", ""),
                    new LlmModel("kimi-k2-thinking-turbo", "Kimi K2 Thinking Turbo", ""),
                    new LlmModel("kimi-k2-turbo-preview", "Kimi K2 Turbo Preview", ""),
                    new LlmModel("kimi-k2-0905-preview", "Kimi K2 0905 Preview", ""),
                    new LlmModel("kimi-k2-0711-preview", "Kimi K2 0711 Preview", ""),
                } },
        new() { Key = "zhipuai", Label = "ZhipuAI", Mark = "智", Cls = "zhipuai", Desc = "智谱AI",
                BaseUrl = "https://open.bigmodel.cn/api/paas/v4", KeyHint = "sk-...", ModelLabel = "模型", DefaultModel = "glm-5.1",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("glm-5.1", "GLM-5.1", ""),
                    new LlmModel("glm-5-turbo", "GLM-5-Turbo", ""),
                    new LlmModel("glm-5", "GLM-5", ""),
                    new LlmModel("glm-4.7", "GLM-4.7", ""),
                    new LlmModel("glm-4.7-flash", "GLM-4.7-Flash", ""),
                    new LlmModel("glm-4.7-flashx", "GLM-4.7-FlashX", ""),
                    new LlmModel("glm-4.6", "GLM-4.6", ""),
                    new LlmModel("glm-4.5", "GLM-4.5", ""),
                    new LlmModel("glm-4.5-x", "GLM-4.5-X", ""),
                    new LlmModel("glm-4.5-air", "GLM-4.5-Air", ""),
                    new LlmModel("glm-4.5-airx", "GLM-4.5-AirX", ""),
                    new LlmModel("glm-4.5-flash", "GLM-4.5-Flash", ""),
                    new LlmModel("glm-z1-air", "GLM-Z1-Air", ""),
                    new LlmModel("glm-z1-flash", "GLM-Z1-Flash", ""),
                    new LlmModel("glm-z1-flashx", "GLM-Z1-FlashX", ""),
                    new LlmModel("codegeex-4", "CodeGeeX-4", ""),
                } },
        new() { Key = "zhipuaicodingplan", Label = "ZhipuAI Coding Plan", Mark = "智", Cls = "zhipuaicodingplan", Desc = "智谱AI Coding Plan",
                BaseUrl = "https://open.bigmodel.cn/api/coding/paas/v4", KeyHint = "sk-...", ModelLabel = "模型", DefaultModel = "glm-5.1",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("glm-5.1", "GLM-5.1", ""),
                    new LlmModel("glm-5-turbo", "GLM-5-Turbo", ""),
                    new LlmModel("glm-4.7", "GLM-4.7", ""),
                    new LlmModel("glm-4.5-air", "GLM-4.5-Air", ""),
                } },
        new() { Key = "minimax", Label = "MiniMax API", Mark = "MM", Cls = "minimax", Desc = "MiniMax",
                BaseUrl = "https://api.minimaxi.com/v1", KeyHint = "Pay-as-you-go API Key", ModelLabel = "模型", DefaultModel = "MiniMax-M2.7",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("MiniMax-M2.7", "MiniMax M2.7", ""),
                    new LlmModel("MiniMax-M2.7-highspeed", "MiniMax M2.7 Highspeed", ""),
                    new LlmModel("MiniMax-M2.5", "MiniMax M2.5", ""),
                    new LlmModel("MiniMax-M2.5-highspeed", "MiniMax M2.5 Highspeed", ""),
                    new LlmModel("MiniMax-M2.1", "MiniMax M2.1", ""),
                    new LlmModel("MiniMax-M2.1-highspeed", "MiniMax M2.1 Highspeed", ""),
                    new LlmModel("MiniMax-M2", "MiniMax M2", ""),
                } },
        new() { Key = "minimaxtokenplan", Label = "MiniMax Token Plan", Mark = "MM", Cls = "minimaxtokenplan", Desc = "MiniMax Token Plan",
                BaseUrl = "https://api.minimaxi.com/v1", KeyHint = "Token Plan API Key", ModelLabel = "模型", DefaultModel = "MiniMax-M2.7",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("MiniMax-M2.7", "MiniMax M2.7", ""),
                    new LlmModel("MiniMax-M2.7-highspeed", "MiniMax M2.7 Highspeed", ""),
                } },
        new() { Key = "qianfan", Label = "Baidu Qianfan", Mark = "度", Cls = "qianfan", Desc = "Baidu Qianfan",
                BaseUrl = "https://qianfan.baidubce.com/v2", KeyHint = "bce-v3/...", ModelLabel = "模型", DefaultModel = "ernie-5.0-thinking-latest",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("ernie-5.0", "ERNIE 5.0", ""),
                    new LlmModel("ernie-5.0-thinking-latest", "ERNIE 5.0 Thinking Latest", ""),
                    new LlmModel("ernie-5.0-thinking-exp", "ERNIE 5.0 Thinking Exp", ""),
                    new LlmModel("ernie-5.0-thinking-preview", "ERNIE 5.0 Thinking Preview", ""),
                    new LlmModel("ernie-4.5-turbo-128k", "ERNIE 4.5 Turbo 128K", ""),
                    new LlmModel("ernie-4.5-turbo-20260402", "ERNIE 4.5 Turbo (2026-04-02)", ""),
                    new LlmModel("ernie-4.5-turbo-128k-preview", "ERNIE 4.5 Turbo 128K Preview", ""),
                    new LlmModel("ernie-4.5-turbo-32k", "ERNIE 4.5 Turbo 32K", ""),
                    new LlmModel("ernie-x1.1", "ERNIE X1.1", ""),
                    new LlmModel("ernie-x1.1-preview", "ERNIE X1.1 Preview", ""),
                    new LlmModel("ernie-x1-turbo-32k", "ERNIE X1 Turbo 32K", ""),
                    new LlmModel("ernie-x1-turbo-32k-preview", "ERNIE X1 Turbo 32K Preview", ""),
                    new LlmModel("ernie-4.5-21b-a3b-thinking", "ERNIE 4.5 21B A3B Thinking", ""),
                    new LlmModel("ernie-char-8k", "ERNIE Character 8K", ""),
                    new LlmModel("ernie-4.5-0.3b", "ERNIE 4.5 0.3B", ""),
                    new LlmModel("ernie-4.5-21b-a3b", "ERNIE 4.5 21B A3B", ""),
                    new LlmModel("ernie-speed-128k", "ERNIE Speed 128K", ""),
                    new LlmModel("ernie-speed-8k", "ERNIE Speed 8K", ""),
                    new LlmModel("ernie-speed-pro-128k", "ERNIE Speed Pro 128K", ""),
                    new LlmModel("ernie-lite-8k", "ERNIE Lite 8K", ""),
                    new LlmModel("ernie-lite-pro-128k", "ERNIE Lite Pro 128K", ""),
                    new LlmModel("ernie-tiny-8k", "ERNIE Tiny 8K", ""),
                    new LlmModel("qianfan-lightning-128b-a19b", "Qianfan Lightning 128B A19B", ""),
                    new LlmModel("qianfan-toytalk", "Qianfan ToyTalk", ""),
                    new LlmModel("qianfan-8b", "Qianfan 8B", ""),
                    new LlmModel("qianfan-70b", "Qianfan 70B", ""),
                    new LlmModel("deepseek-v3.2-think", "DeepSeek V3.2 Think", ""),
                    new LlmModel("deepseek-v3.2", "DeepSeek V3.2", ""),
                    new LlmModel("deepseek-v3.1-250821", "DeepSeek V3.1 250821", ""),
                    new LlmModel("deepseek-v3", "DeepSeek V3", ""),
                    new LlmModel("deepseek-v3.1-think-250821", "DeepSeek V3.1 Think 250821", ""),
                    new LlmModel("deepseek-r1-250528", "DeepSeek R1 250528", ""),
                    new LlmModel("deepseek-r1", "DeepSeek R1", ""),
                    new LlmModel("deepseek-r1-distill-qianfan-70b", "DeepSeek R1 Distill Qianfan 70B", ""),
                    new LlmModel("deepseek-r1-distill-qwen-32b", "DeepSeek R1 Distill Qwen 32B", ""),
                    new LlmModel("qwen3-next-80b-a3b-thinking", "Qwen3 Next 80B A3B Thinking", ""),
                    new LlmModel("qwen3-next-80b-a3b-instruct", "Qwen3 Next 80B A3B Instruct", ""),
                    new LlmModel("qwen3-235b-a22b-thinking-2507", "Qwen3 235B A22B Thinking 2507", ""),
                    new LlmModel("qwen3-235b-a22b-instruct-2507", "Qwen3 235B A22B Instruct 2507", ""),
                    new LlmModel("qwen3-235b-a22b", "Qwen3 235B A22B", ""),
                    new LlmModel("qwen3-30b-a3b", "Qwen3 30B A3B", ""),
                    new LlmModel("qwen3-30b-a3b-instruct-2507", "Qwen3 30B A3B Instruct 2507", ""),
                    new LlmModel("qwen3-32b", "Qwen3 32B", ""),
                    new LlmModel("qwen3-14b", "Qwen3 14B", ""),
                    new LlmModel("qwen3-8b", "Qwen3 8B", ""),
                    new LlmModel("qwen3-4b", "Qwen3 4B", ""),
                    new LlmModel("qwen3-1.7b", "Qwen3 1.7B", ""),
                    new LlmModel("qwen3-0.6b", "Qwen3 0.6B", ""),
                    new LlmModel("kimi-k2-instruct", "Kimi K2 Instruct", ""),
                    new LlmModel("glm-4-32b-0414", "GLM-4 32B 0414", ""),
                    new LlmModel("ernie-4.5-turbo-vl", "ERNIE 4.5 Turbo VL", ""),
                    new LlmModel("ernie-4.5-turbo-vl-32k", "ERNIE 4.5 Turbo VL 32K", ""),
                    new LlmModel("ernie-4.5-vl-28b-a3b", "ERNIE 4.5 VL 28B A3B", ""),
                    new LlmModel("qianfan-vl-1.5-flash", "Qianfan VL 1.5 Flash", ""),
                    new LlmModel("qianfan-composition", "Qianfan Composition", ""),
                    new LlmModel("qianfan-check-vl", "Qianfan Check VL", ""),
                    new LlmModel("qianfan-multipicocr", "Qianfan Multi-Pic OCR", ""),
                    new LlmModel("qianfan-singlepicocr", "Qianfan Single-Pic OCR", ""),
                    new LlmModel("qianfan-vl-70b", "Qianfan VL 70B", ""),
                    new LlmModel("qwen3-vl-32b-instruct", "Qwen3 VL 32B Instruct", ""),
                    new LlmModel("qwen3-vl-32b-thinking", "Qwen3 VL 32B Thinking", ""),
                    new LlmModel("qwen2.5-vl-32b-instruct", "Qwen2.5 VL 32B Instruct", ""),
                    new LlmModel("glm-4.5v", "GLM-4.5V", ""),
                    new LlmModel("deepseek-vl2", "DeepSeek VL2", ""),
                    new LlmModel("ernie-4.5-turbo-vl-preview", "ERNIE 4.5 Turbo VL Preview", ""),
                    new LlmModel("ernie-4.5-turbo-vl-32k-preview", "ERNIE 4.5 Turbo VL 32K Preview", ""),
                    new LlmModel("ernie-4.5-8k-preview", "ERNIE 4.5 8K Preview", ""),
                    new LlmModel("qianfan-vl-8b", "Qianfan VL 8B", ""),
                    new LlmModel("qwen3-vl-8b-instruct", "Qwen3 VL 8B Instruct", ""),
                    new LlmModel("qwen3-vl-8b-thinking", "Qwen3 VL 8B Thinking", ""),
                    new LlmModel("qwen3-vl-30b-a3b-instruct", "Qwen3 VL 30B A3B Instruct", ""),
                    new LlmModel("qwen3-vl-30b-a3b-thinking", "Qwen3 VL 30B A3B Thinking", ""),
                    new LlmModel("qwen3-vl-235b-a22b-instruct", "Qwen3 VL 235B A22B Instruct", ""),
                    new LlmModel("qwen3-vl-235b-a22b-thinking", "Qwen3 VL 235B A22B Thinking", ""),
                    new LlmModel("qwen2.5-vl-7b-instruct", "Qwen2.5 VL 7B Instruct", ""),
                } },
        new() { Key = "xiaomimimo", Label = "Xiaomi MiMo", Mark = "Mi", Cls = "xiaomimimo", Desc = "Xiaomi MiMo",
                BaseUrl = "https://api.xiaomimimo.com/v1", KeyHint = "Input Xiaomi MiMo API key", ModelLabel = "模型", DefaultModel = "mimo-v2.5",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("mimo-v2.5", "MiMo-V2.5", ""),
                    new LlmModel("mimo-v2.5-pro", "MiMo-V2.5 Pro", ""),
                    new LlmModel("mimo-v2-pro", "MiMo-V2 Pro", ""),
                    new LlmModel("mimo-v2-omni", "MiMo-V2 Omni", ""),
                    new LlmModel("mimo-v2-flash", "MiMo-V2 Flash", ""),
                } },
        new() { Key = "siliconcloud", Label = "SiliconCloud", Mark = "硅", Cls = "siliconcloud", Desc = "SiliconCloud",
                BaseUrl = "https://api.siliconflow.cn/v1", KeyHint = "sk-...", ModelLabel = "模型", DefaultModel = "Qwen/Qwen3-32B",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("Pro/zai-org/glm-4.7", "GLM-4.7 Pro", ""),
                    new LlmModel("moonshotai/Kimi-K2-Thinking", "Kimi K2 Thinking", ""),
                    new LlmModel("Pro/moonshotai/Kimi-K2-Thinking", "Kimi K2 Thinking Pro", ""),
                    new LlmModel("MiniMaxAI/MiniMax-M2", "MiniMax M2", ""),
                    new LlmModel("tencent/Hunyuan-MT-7B", "Hunyuan MT 7B", ""),
                    new LlmModel("Kwaipilot/KAT-Dev", "KAT Dev", ""),
                    new LlmModel("zai-org/GLM-4.6", "GLM-4.6", ""),
                    new LlmModel("THUDM/GLM-4.5", "GLM-4.5", ""),
                    new LlmModel("THUDM/glm-4.6-9b-0414", "GLM-4.6 9B 0414", ""),
                    new LlmModel("Qwen/Qwen3-Next-80B-A3B-Thinking", "Qwen3 Next 80B A3B Thinking", ""),
                    new LlmModel("Qwen/Qwen3-Next-80B-A3B-Instruct", "Qwen3 Next 80B A3B Instruct", ""),
                    new LlmModel("deepseek-ai/DeepSeek-V3.2-Exp", "DeepSeek V3.2 Exp", ""),
                    new LlmModel("Pro/deepseek-ai/DeepSeek-V3.2-Exp", "DeepSeek V3.2 Exp Pro", ""),
                    new LlmModel("deepseek-ai/DeepSeek-V3.1-Terminus", "DeepSeek V3.1 Terminus", ""),
                    new LlmModel("Pro/deepseek-ai/DeepSeek-V3.1-Terminus", "DeepSeek V3.1 Terminus Pro", ""),
                    new LlmModel("Qwen/Qwen3-Coder-480B-A35B-Instruct", "Qwen3 Coder 480B A35B Instruct", ""),
                    new LlmModel("Qwen/Qwen3-Coder-30B-A3B-Instruct", "Qwen3 Coder 30B A3B Instruct", ""),
                    new LlmModel("baidu/ERNIE-4.5-300B-A47B", "ERNIE 4.5 300B A47B", ""),
                    new LlmModel("moonshotai/Kimi-K2-Instruct-0905", "Kimi K2 Instruct 0905", ""),
                    new LlmModel("Pro/moonshotai/Kimi-K2-Instruct-0905", "Kimi K2 Instruct 0905 Pro", ""),
                    new LlmModel("tencent/Hunyuan-A13B-Instruct", "Hunyuan A13B Instruct", ""),
                    new LlmModel("Qwen/Qwen3-235B-A22B-Thinking-2507", "Qwen3 235B A22B Thinking 2507", ""),
                    new LlmModel("Qwen/Qwen3-235B-A22B-Instruct-2507", "Qwen3 235B A22B Instruct 2507", ""),
                    new LlmModel("Qwen/Qwen3-30B-A3B-Thinking-2507", "Qwen3 30B A3B Thinking 2507", ""),
                    new LlmModel("Qwen/Qwen3-30B-A3B-Instruct-2507", "Qwen3 30B A3B Instruct 2507", ""),
                    new LlmModel("Qwen/Qwen3-235B-A22B", "Qwen3 235B A22B", ""),
                    new LlmModel("Qwen/Qwen3-32B", "Qwen3 32B", ""),
                    new LlmModel("Qwen/Qwen3-30B-A3B", "Qwen3 30B A3B", ""),
                    new LlmModel("Qwen/Qwen3-14B", "Qwen3 14B", ""),
                    new LlmModel("Qwen/Qwen3-8B", "Qwen3 8B", ""),
                    new LlmModel("THUDM/GLM-Z1-Rumination-32B-0414", "GLM-Z1 Rumination 32B 0414", ""),
                    new LlmModel("THUDM/GLM-Z1-32B-0414", "GLM-Z1 32B 0414", ""),
                    new LlmModel("THUDM/GLM-Z1-9B-0414", "GLM-Z1 9B 0414", ""),
                    new LlmModel("THUDM/GLM-4-32B-0414", "GLM-4 32B 0414", ""),
                    new LlmModel("THUDM/glm-4-9b-chat", "GLM-4 9B Chat", ""),
                    new LlmModel("deepseek-ai/DeepSeek-R1", "DeepSeek R1", ""),
                    new LlmModel("deepseek-ai/DeepSeek-V3", "DeepSeek V3", ""),
                    new LlmModel("Pro/deepseek-ai/DeepSeek-R1", "DeepSeek R1 Pro", ""),
                    new LlmModel("Pro/deepseek-ai/DeepSeek-V3", "DeepSeek V3 Pro", ""),
                    new LlmModel("deepseek-ai/DeepSeek-R1-Distill-Qwen-32B", "DeepSeek R1 Distill Qwen 32B", ""),
                    new LlmModel("deepseek-ai/DeepSeek-R1-Distill-Qwen-14B", "DeepSeek R1 Distill Qwen 14B", ""),
                    new LlmModel("Qwen/QwQ-32B", "QwQ 32B", ""),
                    new LlmModel("Qwen/Qwen2.5-72B-Instruct", "Qwen2.5 72B Instruct", ""),
                    new LlmModel("Qwen/Qwen2.5-32B-Instruct", "Qwen2.5 32B Instruct", ""),
                    new LlmModel("Qwen/Qwen2.5-7B-Instruct", "Qwen2.5 7B Instruct", ""),
                    new LlmModel("Qwen/Qwen3-VL-32B-Instruct", "Qwen3 VL 32B Instruct", ""),
                    new LlmModel("Qwen/Qwen3-VL-32B-Thinking", "Qwen3 VL 32B Thinking", ""),
                    new LlmModel("Qwen/Qwen3-Omni-30B-A3B-Instruct", "Qwen3 Omni 30B A3B Instruct", ""),
                    new LlmModel("Qwen/Qwen3-Omni-30B-A3B-Thinking", "Qwen3 Omni 30B A3B Thinking", ""),
                    new LlmModel("Qwen/Qwen3-Omni-30B-A3B-Captioner", "Qwen3 Omni 30B A3B Captioner", ""),
                    new LlmModel("deepseek-ai/DeepSeek-OCR", "DeepSeek OCR", ""),
                    new LlmModel("zai-org/GLM-4.5V", "GLM-4.5V", ""),
                    new LlmModel("Qwen/QVQ-72B-Preview", "QVQ 72B Preview", ""),
                    new LlmModel("Qwen/Qwen2.5-VL-72B-Instruct", "Qwen2.5 VL 72B Instruct", ""),
                } },
        new() { Key = "groq", Label = "Groq", Mark = "Gq", Cls = "groq", Desc = "Groq",
                BaseUrl = "https://api.groq.com/openai/v1", KeyHint = "gsk_...", ModelLabel = "模型", DefaultModel = "meta-llama/llama-4-scout-17b-16e-instruct",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("groq/compound", "Compound", ""),
                    new LlmModel("groq/compound-mini", "Compound Mini", ""),
                    new LlmModel("openai/gpt-oss-120b", "GPT OSS 120B", ""),
                    new LlmModel("openai/gpt-oss-20b", "GPT OSS 20B", ""),
                    new LlmModel("moonshotai/kimi-k2-instruct-0905", "Kimi K2 0905", ""),
                    new LlmModel("meta-llama/llama-4-scout-17b-16e-instruct", "Llama 4 Scout (17Bx16E)", ""),
                    new LlmModel("meta-llama/llama-4-maverick-17b-128e-instruct", "Llama 4 Maverick (17Bx128E)", ""),
                    new LlmModel("qwen/qwen3-32b", "Qwen3 32B", ""),
                    new LlmModel("llama-3.1-8b-instant", "Llama 3.1 8B Instant", ""),
                    new LlmModel("llama-3.3-70b-versatile", "Llama 3.3 70B Versatile", ""),
                    new LlmModel("mistral-saba-24b", "Mistral Saba 24B", ""),
                    new LlmModel("meta-llama/llama-guard-4-12b", "Llama Guard 4 12B", ""),
                    new LlmModel("meta-llama/llama-prompt-guard-2-22m", "Llama Prompt Guard 2 22M", ""),
                    new LlmModel("meta-llama/llama-prompt-guard-2-86m", "Llama Prompt Guard 2 86M", ""),
                    new LlmModel("openai/gpt-oss-safeguard-20b", "Safety GPT OSS 20B", ""),
                } },
        new() { Key = "xai", Label = "xAI", Mark = "x", Cls = "xai", Desc = "xAI",
                BaseUrl = "https://api.x.ai/v1", KeyHint = "xai-...", ModelLabel = "模型", DefaultModel = "grok-4.3",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("grok-4.3", "Grok 4.3", ""),
                    new LlmModel("grok-4.20-reasoning", "Grok 4.20 Reasoning", ""),
                    new LlmModel("grok-4.20-multi-agent", "Grok 4.20 Multi-Agent", ""),
                    new LlmModel("grok-4-1-fast-reasoning", "Grok 4.1 Fast Reasoning", ""),
                    new LlmModel("grok-4-1-fast-non-reasoning", "Grok 4.1 Fast Non-Reasoning", ""),
                    new LlmModel("grok-4-fast-reasoning", "Grok 4 Fast Reasoning", ""),
                    new LlmModel("grok-4-fast-non-reasoning", "Grok 4 Fast Non-Reasoning", ""),
                    new LlmModel("grok-code-fast-1", "Grok Code Fast 1", ""),
                    new LlmModel("grok-4", "Grok 4", ""),
                    new LlmModel("grok-3", "Grok 3", ""),
                    new LlmModel("grok-3-mini", "Grok 3 Mini", ""),
                } },
        new() { Key = "mistralai", Label = "Mistral AI", Mark = "Mi", Cls = "mistralai", Desc = "Mistral AI",
                BaseUrl = "https://api.mistral.ai/v1", KeyHint = "Your Mistral AI API key", ModelLabel = "模型", DefaultModel = "mistral-small-latest",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("mistral-small-latest", "Mistral Small Latest", ""),
                    new LlmModel("mistral-small-2603", "Mistral Small 4 (26.03)", ""),
                    new LlmModel("mistral-large-latest", "Mistral Large Latest", ""),
                    new LlmModel("mistral-large-2512", "Mistral Large 3 (25.12)", ""),
                    new LlmModel("mistral-medium-latest", "Mistral Medium 3.5 Latest", ""),
                    new LlmModel("mistral-medium-2508", "Mistral Medium 3.1 (25.08)", ""),
                    new LlmModel("magistral-medium-latest", "Magistral Medium Latest", ""),
                    new LlmModel("magistral-medium-2509", "Magistral Medium 1.2 (25.09)", ""),
                    new LlmModel("magistral-small-latest", "Magistral Small Latest", ""),
                    new LlmModel("magistral-small-2509", "Magistral Small 1.2 (25.09)", ""),
                    new LlmModel("devstral-large-latest", "Devstral 2 Latest", ""),
                    new LlmModel("devstral-2512", "Devstral 2 (25.12)", ""),
                    new LlmModel("codestral-latest", "Codestral Latest", ""),
                    new LlmModel("ministral-14b-latest", "Ministral 3 14B Latest", ""),
                    new LlmModel("ministral-8b-latest", "Ministral 3 8B Latest", ""),
                    new LlmModel("ministral-3b-latest", "Ministral 3 3B Latest", ""),
                    new LlmModel("mistral-nemo", "Mistral Nemo", ""),
                    new LlmModel("pixtral-large-latest", "Pixtral Large", ""),
                    new LlmModel("pixtral-12b", "Pixtral 12B", ""),
                } },
        new() { Key = "openrouter", Label = "OpenRouter", Mark = "OR", Cls = "openrouter", Desc = "OpenRouter",
                BaseUrl = "https://openrouter.ai/api/v1", KeyHint = "sk-or-...", ModelLabel = "模型", DefaultModel = "openrouter/auto",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("openrouter/auto", "OpenRouter Auto", ""),
                    new LlmModel("openai/gpt-5.5", "OpenAI GPT-5.5", ""),
                    new LlmModel("openai/gpt-5.4", "OpenAI GPT-5.4", ""),
                    new LlmModel("openai/gpt-5.4-mini", "OpenAI GPT-5.4 mini", ""),
                    new LlmModel("anthropic/claude-opus-4.7", "Claude Opus 4.7", ""),
                    new LlmModel("anthropic/claude-sonnet-4.6", "Claude Sonnet 4.6", ""),
                    new LlmModel("anthropic/claude-haiku-4.5", "Claude Haiku 4.5", ""),
                    new LlmModel("google/gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview", ""),
                    new LlmModel("google/gemini-3.1-flash-lite-preview", "Gemini 3.1 Flash-Lite Preview", ""),
                    new LlmModel("google/gemini-3-flash-preview", "Gemini 3 Flash Preview", ""),
                    new LlmModel("deepseek/deepseek-chat-v3.1", "DeepSeek Chat V3.1", ""),
                    new LlmModel("deepseek/deepseek-r1-0528", "DeepSeek R1 0528", ""),
                    new LlmModel("qwen/qwen3-235b-a22b", "Qwen3 235B A22B", ""),
                    new LlmModel("qwen/qwen3-32b", "Qwen3 32B", ""),
                    new LlmModel("meta-llama/llama-3.3-70b-instruct", "Llama 3.3 70B Instruct", ""),
                    new LlmModel("mistralai/mistral-large", "Mistral Large", ""),
                    new LlmModel("google/gemini-2.5-flash-image-preview", "Gemini 2.5 Flash Image Preview", ""),
                    new LlmModel("meta-llama/llama-3.2-11b-vision-instruct", "Llama 3.2 11B Vision Instruct", ""),
                    new LlmModel("meta-llama/llama-3.2-90b-vision-instruct", "Llama 3.2 90B Vision Instruct", ""),
                } },
        new() { Key = "together", Label = "Together AI", Mark = "Tg", Cls = "together", Desc = "Together AI",
                BaseUrl = "https://api.together.xyz/v1", KeyHint = "Enter your Together AI API key", ModelLabel = "模型", DefaultModel = "MiniMaxAI/MiniMax-M2.7",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("MiniMaxAI/MiniMax-M2.7", "MiniMax M2.7", ""),
                    new LlmModel("MiniMaxAI/MiniMax-M2.5", "MiniMax M2.5", ""),
                    new LlmModel("Qwen/Qwen3.5-397B-A17B", "Qwen3.5 397B A17B", ""),
                    new LlmModel("Qwen/Qwen3.5-9B", "Qwen3.5 9B", ""),
                    new LlmModel("zai-org/GLM-5.1", "GLM-5.1", ""),
                    new LlmModel("zai-org/GLM-5", "GLM-5", ""),
                    new LlmModel("moonshotai/Kimi-K2.5", "Kimi K2.5", ""),
                    new LlmModel("moonshotai/Kimi-K2-Thinking", "Kimi K2 Thinking", ""),
                    new LlmModel("moonshotai/Kimi-K2-Instruct-0905", "Kimi K2 Instruct 0905", ""),
                    new LlmModel("deepseek-ai/DeepSeek-V3.1", "DeepSeek V3.1", ""),
                    new LlmModel("deepseek-ai/DeepSeek-R1", "DeepSeek R1", ""),
                    new LlmModel("openai/gpt-oss-120b", "GPT-OSS 120B", ""),
                    new LlmModel("openai/gpt-oss-20b", "GPT-OSS 20B", ""),
                    new LlmModel("zai-org/GLM-4.6", "GLM 4.6", ""),
                    new LlmModel("zai-org/GLM-4.5-Air-FP8", "GLM 4.5 Air FP8", ""),
                    new LlmModel("Qwen/Qwen3-235B-A22B-Thinking-2507", "Qwen3 235B A22B Thinking 2507", ""),
                    new LlmModel("Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8", "Qwen3 Coder 480B A35B Instruct FP8", ""),
                    new LlmModel("meta-llama/Llama-4-Scout-17B-16E-Instruct", "Llama 4 Scout Instruct", ""),
                    new LlmModel("meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", "Llama 4 Maverick Instruct FP8", ""),
                    new LlmModel("meta-llama/Llama-3.3-70B-Instruct-Turbo", "Llama 3.3 70B Instruct Turbo", ""),
                    new LlmModel("meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo", "Llama 3.1 405B Instruct Turbo", ""),
                    new LlmModel("Qwen/Qwen2.5-72B-Instruct-Turbo", "Qwen2.5 72B Instruct Turbo", ""),
                } },
        new() { Key = "ollama", Label = "Ollama", Mark = "Ol", Cls = "ollama", Desc = "Ollama",
                BaseUrl = "http://127.0.0.1:11434", KeyHint = "API Key", ModelLabel = "模型", DefaultModel = "llama3.1",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("deepseek-v3.1:671b", "DeepSeek V3.1", ""),
                    new LlmModel("gpt-oss:20b", "GPT-OSS 20B", ""),
                    new LlmModel("gpt-oss:120b", "GPT-OSS 120B", ""),
                    new LlmModel("qwen3-coder:480b", "Qwen3 Coder 480B", ""),
                    new LlmModel("deepseek-r1", "DeepSeek R1", ""),
                    new LlmModel("deepseek-v3", "DeepSeek V3 671B", ""),
                    new LlmModel("llama3.1", "Llama 3.1 8B", ""),
                    new LlmModel("llama3.1:70b", "Llama 3.1 70B", ""),
                    new LlmModel("llama3.1:405b", "Llama 3.1 405B", ""),
                    new LlmModel("codellama", "Code Llama 7B", ""),
                    new LlmModel("codellama:13b", "Code Llama 13B", ""),
                    new LlmModel("codellama:34b", "Code Llama 34B", ""),
                    new LlmModel("codellama:70b", "Code Llama 70B", ""),
                    new LlmModel("qwq", "QwQ 32B", ""),
                    new LlmModel("qwen3", "Qwen3 7B", ""),
                    new LlmModel("qwen2.5:0.5b", "Qwen2.5 0.5B", ""),
                    new LlmModel("qwen2.5:1.5b", "Qwen2.5 1.5B", ""),
                    new LlmModel("qwen2.5", "Qwen2.5 7B", ""),
                    new LlmModel("qwen2.5:72b", "Qwen2.5 72B", ""),
                    new LlmModel("gemma2:2b", "Gemma 2 2B", ""),
                    new LlmModel("gemma2", "Gemma 2 9B", ""),
                    new LlmModel("gemma2:27b", "Gemma 2 27B", ""),
                    new LlmModel("mistral", "Mistral 7B", ""),
                    new LlmModel("mixtral", "Mixtral 8x7B", ""),
                    new LlmModel("mixtral:8x22b", "Mixtral 8x22B", ""),
                } },
        new() { Key = "lmstudio", Label = "LM Studio", Mark = "LM", Cls = "lmstudio", Desc = "LM Studio",
                BaseUrl = "http://127.0.0.1:1234/v1", KeyHint = "API Key", ModelLabel = "模型", DefaultModel = "lmstudio-local",
                Price = "按 token 计费(以所选服务商为准)",
                Models = new[]
                {
                    new LlmModel("lmstudio-local", "LM Studio (Local)", ""),
                } },
    };
}
