import Foundation

// 云端大模型内置目录:常见 OpenAI 兼容服务商 + 模型预设(23 家)。
// 用户选服务商即自动填好 BaseURL 与模型预设;也可在「AI 润色」页自定义增删服务商。
public enum CloudCatalog {
    public static let providers: [CloudProviderUI] = [
        CloudProviderUI(
            key: "openai", label: "OpenAI", mark: "AI", cls: "oa",
            desc: "OpenAI", baseURL: "https://api.openai.com/v1", keyHint: "sk-...", modelLabel: "模型", defaultModel: "gpt-5.4-mini",
            models: [
                CloudModelUI(id: "gpt-5.5", label: "GPT-5.5", note: ""),
                CloudModelUI(id: "gpt-5.5-pro", label: "GPT-5.5 pro", note: ""),
                CloudModelUI(id: "gpt-5.4", label: "GPT-5.4", note: ""),
                CloudModelUI(id: "gpt-5.4-pro", label: "GPT-5.4 pro", note: ""),
                CloudModelUI(id: "gpt-5.4-mini", label: "GPT-5.4 mini", note: ""),
                CloudModelUI(id: "gpt-5.4-nano", label: "GPT-5.4 nano", note: ""),
                CloudModelUI(id: "gpt-5.3-chat-latest", label: "GPT-5.3 Chat", note: ""),
                CloudModelUI(id: "gpt-5.2", label: "GPT-5.2", note: ""),
                CloudModelUI(id: "gpt-5.2-pro", label: "GPT-5.2 pro", note: ""),
                CloudModelUI(id: "gpt-5.2-chat-latest", label: "GPT-5.2 Chat", note: ""),
                CloudModelUI(id: "gpt-5.1", label: "GPT-5.1", note: ""),
                CloudModelUI(id: "gpt-5.1-chat-latest", label: "GPT-5.1 Chat", note: ""),
                CloudModelUI(id: "gpt-5", label: "GPT-5", note: ""),
                CloudModelUI(id: "gpt-5-pro", label: "GPT-5 pro", note: ""),
                CloudModelUI(id: "gpt-5-mini", label: "GPT-5 mini", note: ""),
                CloudModelUI(id: "gpt-5-nano", label: "GPT-5 nano", note: ""),
                CloudModelUI(id: "gpt-5-chat-latest", label: "GPT-5 Chat", note: ""),
                CloudModelUI(id: "o4-mini", label: "o4-mini", note: ""),
                CloudModelUI(id: "o3-pro", label: "o3-pro", note: ""),
                CloudModelUI(id: "o3", label: "o3", note: ""),
                CloudModelUI(id: "o3-mini", label: "o3-mini", note: ""),
                CloudModelUI(id: "gpt-4.1", label: "GPT-4.1", note: ""),
                CloudModelUI(id: "gpt-4.1-mini", label: "GPT-4.1 mini", note: ""),
                CloudModelUI(id: "gpt-4.1-nano", label: "GPT-4.1 nano", note: ""),
                CloudModelUI(id: "chatgpt-4o-latest", label: "ChatGPT-4o", note: ""),
                CloudModelUI(id: "gpt-4o", label: "GPT-4o", note: ""),
                CloudModelUI(id: "gpt-4o-mini", label: "GPT-4o mini", note: ""),
                CloudModelUI(id: "gpt-4-turbo", label: "GPT-4 Turbo", note: ""),
                CloudModelUI(id: "gpt-4", label: "GPT-4", note: ""),
                CloudModelUI(id: "gpt-3.5-turbo", label: "GPT-3.5 Turbo", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "claude", label: "Claude", mark: "Cl", cls: "claude",
            desc: "Anthropic", baseURL: "https://api.anthropic.com", keyHint: "sk-ant-...", modelLabel: "模型", defaultModel: "claude-sonnet-4-6",
            models: [
                CloudModelUI(id: "claude-opus-4-7", label: "Claude Opus 4.7", note: ""),
                CloudModelUI(id: "claude-opus-4-6", label: "Claude Opus 4.6", note: ""),
                CloudModelUI(id: "claude-opus-4-5-20251101", label: "Claude Opus 4.5", note: ""),
                CloudModelUI(id: "claude-opus-4-1-20250805", label: "Claude Opus 4.1", note: ""),
                CloudModelUI(id: "claude-sonnet-4-6", label: "Claude Sonnet 4.6", note: ""),
                CloudModelUI(id: "claude-sonnet-4-5-20250929", label: "Claude Sonnet 4.5", note: ""),
                CloudModelUI(id: "claude-haiku-4-5-20251001", label: "Claude Haiku 4.5", note: ""),
                CloudModelUI(id: "claude-sonnet-4-20250514", label: "Claude Sonnet 4", note: ""),
                CloudModelUI(id: "claude-opus-4-20250514", label: "Claude Opus 4", note: ""),
                CloudModelUI(id: "claude-3-7-sonnet-20250219", label: "Claude Sonnet 3.7", note: ""),
                CloudModelUI(id: "claude-3-5-sonnet-20241022", label: "Claude Sonnet 3.5", note: ""),
                CloudModelUI(id: "claude-3-5-haiku-20241022", label: "Claude Haiku 3.5", note: ""),
                CloudModelUI(id: "claude-3-haiku-20240307", label: "Claude Haiku 3", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "gemini", label: "Google Gemini", mark: "G", cls: "gemini",
            desc: "Google", baseURL: "https://generativelanguage.googleapis.com/v1beta", keyHint: "AIza...", modelLabel: "模型", defaultModel: "gemini-3-flash-preview",
            models: [
                CloudModelUI(id: "gemini-3-flash-preview", label: "Gemini 3 Flash Preview", note: ""),
                CloudModelUI(id: "gemini-3.1-pro-preview", label: "Gemini 3.1 Pro Preview", note: ""),
                CloudModelUI(id: "gemini-3.1-flash-lite-preview", label: "Gemini 3.1 Flash-Lite Preview", note: ""),
                CloudModelUI(id: "gemini-pro-latest", label: "Gemini Pro Latest", note: ""),
                CloudModelUI(id: "gemini-flash-latest", label: "Gemini Flash Latest", note: ""),
                CloudModelUI(id: "gemini-flash-lite-latest", label: "Gemini Flash-Lite Latest", note: ""),
                CloudModelUI(id: "gemini-2.5-pro", label: "Gemini 2.5 Pro", note: ""),
                CloudModelUI(id: "gemini-2.5-flash", label: "Gemini 2.5 Flash", note: ""),
                CloudModelUI(id: "gemini-2.5-flash-lite", label: "Gemini 2.5 Flash-Lite", note: ""),
                CloudModelUI(id: "gemini-2.0-flash", label: "Gemini 2.0 Flash", note: ""),
                CloudModelUI(id: "gemini-2.0-flash-lite", label: "Gemini 2.0 Flash-Lite", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "deepseek", label: "DeepSeek", mark: "DS", cls: "deepseek",
            desc: "DeepSeek", baseURL: "https://api.deepseek.com/v1", keyHint: "API Key", modelLabel: "模型", defaultModel: "deepseek-v4-flash",
            models: [
                CloudModelUI(id: "deepseek-v4-flash", label: "DeepSeek V4 Flash", note: ""),
                CloudModelUI(id: "deepseek-v4-pro", label: "DeepSeek V4 Pro", note: ""),
                CloudModelUI(id: "deepseek-chat", label: "DeepSeek Chat (compatibility)", note: ""),
                CloudModelUI(id: "deepseek-reasoner", label: "DeepSeek Reasoner (compatibility)", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "qwen", label: "Qwen", mark: "通", cls: "qwen",
            desc: "Alibaba Cloud DashScope", baseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1", keyHint: "sk-...", modelLabel: "模型", defaultModel: "qwen3.6-flash",
            models: [
                CloudModelUI(id: "qwen3.6-max-preview", label: "Qwen3.6 Max Preview", note: ""),
                CloudModelUI(id: "qwen3.6-plus", label: "Qwen3.6 Plus", note: ""),
                CloudModelUI(id: "qwen3.6-plus-2026-04-02", label: "Qwen3.6 Plus (2026-04-02)", note: ""),
                CloudModelUI(id: "qwen3.6-flash", label: "Qwen3.6 Flash", note: ""),
                CloudModelUI(id: "qwen3.6-flash-2026-04-16", label: "Qwen3.6 Flash (2026-04-16)", note: ""),
                CloudModelUI(id: "qwen3.5-plus", label: "Qwen3.5 Plus", note: ""),
                CloudModelUI(id: "qwen3.5-plus-2026-02-15", label: "Qwen3.5 Plus (2026-02-15)", note: ""),
                CloudModelUI(id: "qwen3.5-flash", label: "Qwen3.5 Flash", note: ""),
                CloudModelUI(id: "qwen3.5-flash-2026-02-23", label: "Qwen3.5 Flash (2026-02-23)", note: ""),
                CloudModelUI(id: "qwen3.5-397b-a17b", label: "Qwen3.5 397B A17B", note: ""),
                CloudModelUI(id: "qwen3.5-122b-a10b", label: "Qwen3.5 122B A10B", note: ""),
                CloudModelUI(id: "qwen3.5-27b", label: "Qwen3.5 27B", note: ""),
                CloudModelUI(id: "qwen3.5-35b-a3b", label: "Qwen3.5 35B A3B", note: ""),
                CloudModelUI(id: "deepseek-v4-pro", label: "DeepSeek V4 Pro", note: ""),
                CloudModelUI(id: "deepseek-v4-flash", label: "DeepSeek V4 Flash", note: ""),
                CloudModelUI(id: "glm-5.1", label: "GLM-5.1", note: ""),
                CloudModelUI(id: "kimi-k2.6", label: "Kimi K2.6", note: ""),
                CloudModelUI(id: "kimi-k2.5", label: "Kimi K2.5", note: ""),
                CloudModelUI(id: "MiniMax-M2.5", label: "MiniMax M2.5", note: ""),
                CloudModelUI(id: "qwen3-max", label: "Qwen3 Max", note: ""),
                CloudModelUI(id: "qwen3-max-2026-01-23", label: "Qwen3 Max (2026-01-23)", note: ""),
                CloudModelUI(id: "qwen3-max-preview", label: "Qwen3 Max Preview", note: ""),
                CloudModelUI(id: "qwen3-max-2025-09-23", label: "Qwen3 Max (2025-09-23)", note: ""),
                CloudModelUI(id: "qwen3-coder-next", label: "Qwen3 Coder Next", note: ""),
                CloudModelUI(id: "qwen3-coder-480b-a35b-instruct", label: "Qwen3 Coder 480B A35B Instruct", note: ""),
                CloudModelUI(id: "qwen3-coder-30b-a3b-instruct", label: "Qwen3 Coder 30B A3B Instruct", note: ""),
                CloudModelUI(id: "qwen3-coder-plus", label: "Qwen3 Coder Plus", note: ""),
                CloudModelUI(id: "qwen3-coder-plus-2025-09-23", label: "Qwen3 Coder Plus (2025-09-23)", note: ""),
                CloudModelUI(id: "qwen3-coder-plus-2025-07-22", label: "Qwen3 Coder Plus (2025-07-22)", note: ""),
                CloudModelUI(id: "qwen3-coder-flash", label: "Qwen3 Coder Flash", note: ""),
                CloudModelUI(id: "qwen3-coder-flash-2025-07-28", label: "Qwen3 Coder Flash (2025-07-28)", note: ""),
                CloudModelUI(id: "qwen3-235b-a22b", label: "Qwen3 235B A22B", note: ""),
                CloudModelUI(id: "qwen3-235b-a22b-thinking-2507", label: "Qwen3 235B A22B Thinking 2507", note: ""),
                CloudModelUI(id: "qwen3-235b-a22b-instruct-2507", label: "Qwen3 235B A22B Instruct 2507", note: ""),
                CloudModelUI(id: "qwen3-next-80b-a3b-thinking", label: "Qwen3 Next 80B A3B Thinking", note: ""),
                CloudModelUI(id: "qwen3-next-80b-a3b-instruct", label: "Qwen3 Next 80B A3B Instruct", note: ""),
                CloudModelUI(id: "qwen3-32b", label: "Qwen3 32B", note: ""),
                CloudModelUI(id: "qwen3-30b-a3b", label: "Qwen3 30B A3B", note: ""),
                CloudModelUI(id: "qwen3-14b", label: "Qwen3 14B", note: ""),
                CloudModelUI(id: "qwen3-8b", label: "Qwen3 8B", note: ""),
                CloudModelUI(id: "qwen3-4b", label: "Qwen3 4B", note: ""),
                CloudModelUI(id: "qwen3-1.7b", label: "Qwen3 1.7B", note: ""),
                CloudModelUI(id: "qwen3-0.6b", label: "Qwen3 0.6B", note: ""),
                CloudModelUI(id: "qwen-plus", label: "Qwen Plus", note: ""),
                CloudModelUI(id: "qwen-flash", label: "Qwen Flash", note: ""),
                CloudModelUI(id: "qwen-plus-us", label: "Qwen Plus US", note: ""),
                CloudModelUI(id: "qwen-flash-us", label: "Qwen Flash US", note: ""),
                CloudModelUI(id: "qwen-turbo", label: "Qwen Turbo", note: ""),
                CloudModelUI(id: "qwen-long", label: "Qwen Long", note: ""),
                CloudModelUI(id: "qwq-plus", label: "QwQ Plus", note: ""),
                CloudModelUI(id: "qwq-32b", label: "QwQ 32B", note: ""),
                CloudModelUI(id: "qwen2.5-72b-instruct", label: "Qwen2.5 72B Instruct", note: ""),
                CloudModelUI(id: "qwen2.5-32b-instruct", label: "Qwen2.5 32B Instruct", note: ""),
                CloudModelUI(id: "qwen2.5-14b-instruct", label: "Qwen2.5 14B Instruct", note: ""),
                CloudModelUI(id: "qwen2.5-7b-instruct", label: "Qwen2.5 7B Instruct", note: ""),
                CloudModelUI(id: "qwen3-vl-plus", label: "Qwen3 VL Plus", note: ""),
                CloudModelUI(id: "qwen3-vl-flash", label: "Qwen3 VL Flash", note: ""),
                CloudModelUI(id: "qwen-vl-plus", label: "Qwen VL Plus", note: ""),
                CloudModelUI(id: "qwen-vl-max", label: "Qwen VL Max", note: ""),
                CloudModelUI(id: "qwen-vl-ocr", label: "Qwen VL OCR", note: ""),
                CloudModelUI(id: "qwen3-omni-flash", label: "Qwen3 Omni Flash", note: ""),
                CloudModelUI(id: "qwen-omni-turbo", label: "Qwen Omni Turbo", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "aliyun", label: "Alibaba Cloud Bailian", mark: "百", cls: "aliyun",
            desc: "Alibaba Cloud DashScope", baseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1", keyHint: "sk-...", modelLabel: "模型", defaultModel: "deepseek-v4-flash",
            models: [
                CloudModelUI(id: "deepseek-v4-pro", label: "DeepSeek V4 Pro", note: ""),
                CloudModelUI(id: "deepseek-v4-flash", label: "DeepSeek V4 Flash", note: ""),
                CloudModelUI(id: "deepseek-v3", label: "DeepSeek V3", note: ""),
                CloudModelUI(id: "deepseek-r1", label: "DeepSeek R1", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "doubao", label: "Doubao / Volcengine Ark", mark: "豆", cls: "doubao",
            desc: "Volcano Ark", baseURL: "https://ark.cn-beijing.volces.com/api/v3", keyHint: "ARK_API_KEY", modelLabel: "模型", defaultModel: "doubao-seed-1.6",
            models: [
                CloudModelUI(id: "doubao-seed-1.6", label: "Doubao Seed 1.6", note: ""),
                CloudModelUI(id: "doubao-seed-1.6-thinking", label: "Doubao Seed 1.6 Thinking", note: ""),
                CloudModelUI(id: "doubao-seed-1.6-flash", label: "Doubao Seed 1.6 Flash", note: ""),
                CloudModelUI(id: "doubao-seed-code-preview-251028", label: "Doubao Seed Code Preview 251028", note: ""),
                CloudModelUI(id: "doubao-1.5-thinking-pro", label: "Doubao 1.5 Thinking Pro", note: ""),
                CloudModelUI(id: "doubao-1.5-pro-32k", label: "Doubao 1.5 Pro 32K", note: ""),
                CloudModelUI(id: "doubao-1.5-lite-32k", label: "Doubao 1.5 Lite 32K", note: ""),
                CloudModelUI(id: "doubao-lite-128k", label: "Doubao Lite 128K", note: ""),
                CloudModelUI(id: "doubao-lite-32k", label: "Doubao Lite 32K", note: ""),
                CloudModelUI(id: "doubao-1.5-vision-pro-32k", label: "Doubao 1.5 Vision Pro 32K", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "moonshot", label: "Moonshot AI", mark: "Ki", cls: "moonshot",
            desc: "Moonshot AI", baseURL: "https://api.moonshot.cn/v1", keyHint: "sk-...", modelLabel: "模型", defaultModel: "kimi-k2.6",
            models: [
                CloudModelUI(id: "kimi-k2.6", label: "Kimi K2.6", note: ""),
                CloudModelUI(id: "kimi-k2.5", label: "Kimi K2.5", note: ""),
                CloudModelUI(id: "kimi-k2-thinking", label: "Kimi K2 Thinking", note: ""),
                CloudModelUI(id: "kimi-k2-thinking-turbo", label: "Kimi K2 Thinking Turbo", note: ""),
                CloudModelUI(id: "kimi-k2-turbo-preview", label: "Kimi K2 Turbo Preview", note: ""),
                CloudModelUI(id: "kimi-k2-0905-preview", label: "Kimi K2 0905 Preview", note: ""),
                CloudModelUI(id: "kimi-k2-0711-preview", label: "Kimi K2 0711 Preview", note: ""),
                CloudModelUI(id: "moonshot-v1-8k", label: "Moonshot V1 8K", note: ""),
                CloudModelUI(id: "moonshot-v1-32k", label: "Moonshot V1 32K", note: ""),
                CloudModelUI(id: "moonshot-v1-128k", label: "Moonshot V1 128K", note: ""),
                CloudModelUI(id: "moonshot-v1-8k-vision-preview", label: "Moonshot V1 8K Vision Preview", note: ""),
                CloudModelUI(id: "moonshot-v1-32k-vision-preview", label: "Moonshot V1 32K Vision Preview", note: ""),
                CloudModelUI(id: "moonshot-v1-128k-vision-preview", label: "Moonshot V1 128K Vision Preview", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "kimicodingplan", label: "Kimi Coding Plan", mark: "Ki", cls: "kimicodingplan",
            desc: "Kimi Coding Plan", baseURL: "https://api.moonshot.cn/anthropic", keyHint: "sk-...", modelLabel: "模型", defaultModel: "kimi-k2.6",
            models: [
                CloudModelUI(id: "kimi-k2.6", label: "Kimi K2.6", note: ""),
                CloudModelUI(id: "kimi-k2.5", label: "Kimi K2.5", note: ""),
                CloudModelUI(id: "kimi-k2-thinking", label: "Kimi K2 Thinking", note: ""),
                CloudModelUI(id: "kimi-k2-thinking-turbo", label: "Kimi K2 Thinking Turbo", note: ""),
                CloudModelUI(id: "kimi-k2-turbo-preview", label: "Kimi K2 Turbo Preview", note: ""),
                CloudModelUI(id: "kimi-k2-0905-preview", label: "Kimi K2 0905 Preview", note: ""),
                CloudModelUI(id: "kimi-k2-0711-preview", label: "Kimi K2 0711 Preview", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "zhipuai", label: "ZhipuAI", mark: "智", cls: "zhipuai",
            desc: "智谱AI", baseURL: "https://open.bigmodel.cn/api/paas/v4", keyHint: "sk-...", modelLabel: "模型", defaultModel: "glm-5.1",
            models: [
                CloudModelUI(id: "glm-5.1", label: "GLM-5.1", note: ""),
                CloudModelUI(id: "glm-5-turbo", label: "GLM-5-Turbo", note: ""),
                CloudModelUI(id: "glm-5", label: "GLM-5", note: ""),
                CloudModelUI(id: "glm-4.7", label: "GLM-4.7", note: ""),
                CloudModelUI(id: "glm-4.7-flash", label: "GLM-4.7-Flash", note: ""),
                CloudModelUI(id: "glm-4.7-flashx", label: "GLM-4.7-FlashX", note: ""),
                CloudModelUI(id: "glm-4.6", label: "GLM-4.6", note: ""),
                CloudModelUI(id: "glm-4.5", label: "GLM-4.5", note: ""),
                CloudModelUI(id: "glm-4.5-x", label: "GLM-4.5-X", note: ""),
                CloudModelUI(id: "glm-4.5-air", label: "GLM-4.5-Air", note: ""),
                CloudModelUI(id: "glm-4.5-airx", label: "GLM-4.5-AirX", note: ""),
                CloudModelUI(id: "glm-4.5-flash", label: "GLM-4.5-Flash", note: ""),
                CloudModelUI(id: "glm-z1-air", label: "GLM-Z1-Air", note: ""),
                CloudModelUI(id: "glm-z1-flash", label: "GLM-Z1-Flash", note: ""),
                CloudModelUI(id: "glm-z1-flashx", label: "GLM-Z1-FlashX", note: ""),
                CloudModelUI(id: "codegeex-4", label: "CodeGeeX-4", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "zhipuaicodingplan", label: "ZhipuAI Coding Plan", mark: "智", cls: "zhipuaicodingplan",
            desc: "智谱AI Coding Plan", baseURL: "https://open.bigmodel.cn/api/coding/paas/v4", keyHint: "sk-...", modelLabel: "模型", defaultModel: "glm-5.1",
            models: [
                CloudModelUI(id: "glm-5.1", label: "GLM-5.1", note: ""),
                CloudModelUI(id: "glm-5-turbo", label: "GLM-5-Turbo", note: ""),
                CloudModelUI(id: "glm-4.7", label: "GLM-4.7", note: ""),
                CloudModelUI(id: "glm-4.5-air", label: "GLM-4.5-Air", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "minimax", label: "MiniMax API", mark: "MM", cls: "minimax",
            desc: "MiniMax", baseURL: "https://api.minimaxi.com/v1", keyHint: "Pay-as-you-go API Key", modelLabel: "模型", defaultModel: "MiniMax-M2.7",
            models: [
                CloudModelUI(id: "MiniMax-M2.7", label: "MiniMax M2.7", note: ""),
                CloudModelUI(id: "MiniMax-M2.7-highspeed", label: "MiniMax M2.7 Highspeed", note: ""),
                CloudModelUI(id: "MiniMax-M2.5", label: "MiniMax M2.5", note: ""),
                CloudModelUI(id: "MiniMax-M2.5-highspeed", label: "MiniMax M2.5 Highspeed", note: ""),
                CloudModelUI(id: "MiniMax-M2.1", label: "MiniMax M2.1", note: ""),
                CloudModelUI(id: "MiniMax-M2.1-highspeed", label: "MiniMax M2.1 Highspeed", note: ""),
                CloudModelUI(id: "MiniMax-M2", label: "MiniMax M2", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "minimaxtokenplan", label: "MiniMax Token Plan", mark: "MM", cls: "minimaxtokenplan",
            desc: "MiniMax Token Plan", baseURL: "https://api.minimaxi.com/v1", keyHint: "Token Plan API Key", modelLabel: "模型", defaultModel: "MiniMax-M2.7",
            models: [
                CloudModelUI(id: "MiniMax-M2.7", label: "MiniMax M2.7", note: ""),
                CloudModelUI(id: "MiniMax-M2.7-highspeed", label: "MiniMax M2.7 Highspeed", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "qianfan", label: "Baidu Qianfan", mark: "度", cls: "qianfan",
            desc: "Baidu Qianfan", baseURL: "https://qianfan.baidubce.com/v2", keyHint: "bce-v3/...", modelLabel: "模型", defaultModel: "ernie-5.0-thinking-latest",
            models: [
                CloudModelUI(id: "ernie-5.0", label: "ERNIE 5.0", note: ""),
                CloudModelUI(id: "ernie-5.0-thinking-latest", label: "ERNIE 5.0 Thinking Latest", note: ""),
                CloudModelUI(id: "ernie-5.0-thinking-exp", label: "ERNIE 5.0 Thinking Exp", note: ""),
                CloudModelUI(id: "ernie-5.0-thinking-preview", label: "ERNIE 5.0 Thinking Preview", note: ""),
                CloudModelUI(id: "ernie-4.5-turbo-128k", label: "ERNIE 4.5 Turbo 128K", note: ""),
                CloudModelUI(id: "ernie-4.5-turbo-20260402", label: "ERNIE 4.5 Turbo (2026-04-02)", note: ""),
                CloudModelUI(id: "ernie-4.5-turbo-128k-preview", label: "ERNIE 4.5 Turbo 128K Preview", note: ""),
                CloudModelUI(id: "ernie-4.5-turbo-32k", label: "ERNIE 4.5 Turbo 32K", note: ""),
                CloudModelUI(id: "ernie-x1.1", label: "ERNIE X1.1", note: ""),
                CloudModelUI(id: "ernie-x1.1-preview", label: "ERNIE X1.1 Preview", note: ""),
                CloudModelUI(id: "ernie-x1-turbo-32k", label: "ERNIE X1 Turbo 32K", note: ""),
                CloudModelUI(id: "ernie-x1-turbo-32k-preview", label: "ERNIE X1 Turbo 32K Preview", note: ""),
                CloudModelUI(id: "ernie-4.5-21b-a3b-thinking", label: "ERNIE 4.5 21B A3B Thinking", note: ""),
                CloudModelUI(id: "ernie-char-8k", label: "ERNIE Character 8K", note: ""),
                CloudModelUI(id: "ernie-4.5-0.3b", label: "ERNIE 4.5 0.3B", note: ""),
                CloudModelUI(id: "ernie-4.5-21b-a3b", label: "ERNIE 4.5 21B A3B", note: ""),
                CloudModelUI(id: "ernie-speed-128k", label: "ERNIE Speed 128K", note: ""),
                CloudModelUI(id: "ernie-speed-8k", label: "ERNIE Speed 8K", note: ""),
                CloudModelUI(id: "ernie-speed-pro-128k", label: "ERNIE Speed Pro 128K", note: ""),
                CloudModelUI(id: "ernie-lite-8k", label: "ERNIE Lite 8K", note: ""),
                CloudModelUI(id: "ernie-lite-pro-128k", label: "ERNIE Lite Pro 128K", note: ""),
                CloudModelUI(id: "ernie-tiny-8k", label: "ERNIE Tiny 8K", note: ""),
                CloudModelUI(id: "qianfan-lightning-128b-a19b", label: "Qianfan Lightning 128B A19B", note: ""),
                CloudModelUI(id: "qianfan-toytalk", label: "Qianfan ToyTalk", note: ""),
                CloudModelUI(id: "qianfan-8b", label: "Qianfan 8B", note: ""),
                CloudModelUI(id: "qianfan-70b", label: "Qianfan 70B", note: ""),
                CloudModelUI(id: "deepseek-v3.2-think", label: "DeepSeek V3.2 Think", note: ""),
                CloudModelUI(id: "deepseek-v3.2", label: "DeepSeek V3.2", note: ""),
                CloudModelUI(id: "deepseek-v3.1-250821", label: "DeepSeek V3.1 250821", note: ""),
                CloudModelUI(id: "deepseek-v3", label: "DeepSeek V3", note: ""),
                CloudModelUI(id: "deepseek-v3.1-think-250821", label: "DeepSeek V3.1 Think 250821", note: ""),
                CloudModelUI(id: "deepseek-r1-250528", label: "DeepSeek R1 250528", note: ""),
                CloudModelUI(id: "deepseek-r1", label: "DeepSeek R1", note: ""),
                CloudModelUI(id: "deepseek-r1-distill-qianfan-70b", label: "DeepSeek R1 Distill Qianfan 70B", note: ""),
                CloudModelUI(id: "deepseek-r1-distill-qwen-32b", label: "DeepSeek R1 Distill Qwen 32B", note: ""),
                CloudModelUI(id: "qwen3-next-80b-a3b-thinking", label: "Qwen3 Next 80B A3B Thinking", note: ""),
                CloudModelUI(id: "qwen3-next-80b-a3b-instruct", label: "Qwen3 Next 80B A3B Instruct", note: ""),
                CloudModelUI(id: "qwen3-235b-a22b-thinking-2507", label: "Qwen3 235B A22B Thinking 2507", note: ""),
                CloudModelUI(id: "qwen3-235b-a22b-instruct-2507", label: "Qwen3 235B A22B Instruct 2507", note: ""),
                CloudModelUI(id: "qwen3-235b-a22b", label: "Qwen3 235B A22B", note: ""),
                CloudModelUI(id: "qwen3-30b-a3b", label: "Qwen3 30B A3B", note: ""),
                CloudModelUI(id: "qwen3-30b-a3b-instruct-2507", label: "Qwen3 30B A3B Instruct 2507", note: ""),
                CloudModelUI(id: "qwen3-32b", label: "Qwen3 32B", note: ""),
                CloudModelUI(id: "qwen3-14b", label: "Qwen3 14B", note: ""),
                CloudModelUI(id: "qwen3-8b", label: "Qwen3 8B", note: ""),
                CloudModelUI(id: "qwen3-4b", label: "Qwen3 4B", note: ""),
                CloudModelUI(id: "qwen3-1.7b", label: "Qwen3 1.7B", note: ""),
                CloudModelUI(id: "qwen3-0.6b", label: "Qwen3 0.6B", note: ""),
                CloudModelUI(id: "kimi-k2-instruct", label: "Kimi K2 Instruct", note: ""),
                CloudModelUI(id: "glm-4-32b-0414", label: "GLM-4 32B 0414", note: ""),
                CloudModelUI(id: "ernie-4.5-turbo-vl", label: "ERNIE 4.5 Turbo VL", note: ""),
                CloudModelUI(id: "ernie-4.5-turbo-vl-32k", label: "ERNIE 4.5 Turbo VL 32K", note: ""),
                CloudModelUI(id: "ernie-4.5-vl-28b-a3b", label: "ERNIE 4.5 VL 28B A3B", note: ""),
                CloudModelUI(id: "qianfan-vl-1.5-flash", label: "Qianfan VL 1.5 Flash", note: ""),
                CloudModelUI(id: "qianfan-composition", label: "Qianfan Composition", note: ""),
                CloudModelUI(id: "qianfan-check-vl", label: "Qianfan Check VL", note: ""),
                CloudModelUI(id: "qianfan-multipicocr", label: "Qianfan Multi-Pic OCR", note: ""),
                CloudModelUI(id: "qianfan-singlepicocr", label: "Qianfan Single-Pic OCR", note: ""),
                CloudModelUI(id: "qianfan-vl-70b", label: "Qianfan VL 70B", note: ""),
                CloudModelUI(id: "qwen3-vl-32b-instruct", label: "Qwen3 VL 32B Instruct", note: ""),
                CloudModelUI(id: "qwen3-vl-32b-thinking", label: "Qwen3 VL 32B Thinking", note: ""),
                CloudModelUI(id: "qwen2.5-vl-32b-instruct", label: "Qwen2.5 VL 32B Instruct", note: ""),
                CloudModelUI(id: "glm-4.5v", label: "GLM-4.5V", note: ""),
                CloudModelUI(id: "deepseek-vl2", label: "DeepSeek VL2", note: ""),
                CloudModelUI(id: "ernie-4.5-turbo-vl-preview", label: "ERNIE 4.5 Turbo VL Preview", note: ""),
                CloudModelUI(id: "ernie-4.5-turbo-vl-32k-preview", label: "ERNIE 4.5 Turbo VL 32K Preview", note: ""),
                CloudModelUI(id: "ernie-4.5-8k-preview", label: "ERNIE 4.5 8K Preview", note: ""),
                CloudModelUI(id: "qianfan-vl-8b", label: "Qianfan VL 8B", note: ""),
                CloudModelUI(id: "qwen3-vl-8b-instruct", label: "Qwen3 VL 8B Instruct", note: ""),
                CloudModelUI(id: "qwen3-vl-8b-thinking", label: "Qwen3 VL 8B Thinking", note: ""),
                CloudModelUI(id: "qwen3-vl-30b-a3b-instruct", label: "Qwen3 VL 30B A3B Instruct", note: ""),
                CloudModelUI(id: "qwen3-vl-30b-a3b-thinking", label: "Qwen3 VL 30B A3B Thinking", note: ""),
                CloudModelUI(id: "qwen3-vl-235b-a22b-instruct", label: "Qwen3 VL 235B A22B Instruct", note: ""),
                CloudModelUI(id: "qwen3-vl-235b-a22b-thinking", label: "Qwen3 VL 235B A22B Thinking", note: ""),
                CloudModelUI(id: "qwen2.5-vl-7b-instruct", label: "Qwen2.5 VL 7B Instruct", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "xiaomimimo", label: "Xiaomi MiMo", mark: "Mi", cls: "xiaomimimo",
            desc: "Xiaomi MiMo", baseURL: "https://api.xiaomimimo.com/v1", keyHint: "Input Xiaomi MiMo API key", modelLabel: "模型", defaultModel: "mimo-v2.5",
            models: [
                CloudModelUI(id: "mimo-v2.5", label: "MiMo-V2.5", note: ""),
                CloudModelUI(id: "mimo-v2.5-pro", label: "MiMo-V2.5 Pro", note: ""),
                CloudModelUI(id: "mimo-v2-pro", label: "MiMo-V2 Pro", note: ""),
                CloudModelUI(id: "mimo-v2-omni", label: "MiMo-V2 Omni", note: ""),
                CloudModelUI(id: "mimo-v2-flash", label: "MiMo-V2 Flash", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "siliconcloud", label: "SiliconCloud", mark: "硅", cls: "siliconcloud",
            desc: "SiliconCloud", baseURL: "https://api.siliconflow.cn/v1", keyHint: "sk-...", modelLabel: "模型", defaultModel: "Qwen/Qwen3-32B",
            models: [
                CloudModelUI(id: "Pro/zai-org/glm-4.7", label: "GLM-4.7 Pro", note: ""),
                CloudModelUI(id: "moonshotai/Kimi-K2-Thinking", label: "Kimi K2 Thinking", note: ""),
                CloudModelUI(id: "Pro/moonshotai/Kimi-K2-Thinking", label: "Kimi K2 Thinking Pro", note: ""),
                CloudModelUI(id: "MiniMaxAI/MiniMax-M2", label: "MiniMax M2", note: ""),
                CloudModelUI(id: "tencent/Hunyuan-MT-7B", label: "Hunyuan MT 7B", note: ""),
                CloudModelUI(id: "Kwaipilot/KAT-Dev", label: "KAT Dev", note: ""),
                CloudModelUI(id: "zai-org/GLM-4.6", label: "GLM-4.6", note: ""),
                CloudModelUI(id: "THUDM/GLM-4.5", label: "GLM-4.5", note: ""),
                CloudModelUI(id: "THUDM/glm-4.6-9b-0414", label: "GLM-4.6 9B 0414", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-Next-80B-A3B-Thinking", label: "Qwen3 Next 80B A3B Thinking", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-Next-80B-A3B-Instruct", label: "Qwen3 Next 80B A3B Instruct", note: ""),
                CloudModelUI(id: "deepseek-ai/DeepSeek-V3.2-Exp", label: "DeepSeek V3.2 Exp", note: ""),
                CloudModelUI(id: "Pro/deepseek-ai/DeepSeek-V3.2-Exp", label: "DeepSeek V3.2 Exp Pro", note: ""),
                CloudModelUI(id: "deepseek-ai/DeepSeek-V3.1-Terminus", label: "DeepSeek V3.1 Terminus", note: ""),
                CloudModelUI(id: "Pro/deepseek-ai/DeepSeek-V3.1-Terminus", label: "DeepSeek V3.1 Terminus Pro", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-Coder-480B-A35B-Instruct", label: "Qwen3 Coder 480B A35B Instruct", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-Coder-30B-A3B-Instruct", label: "Qwen3 Coder 30B A3B Instruct", note: ""),
                CloudModelUI(id: "baidu/ERNIE-4.5-300B-A47B", label: "ERNIE 4.5 300B A47B", note: ""),
                CloudModelUI(id: "moonshotai/Kimi-K2-Instruct-0905", label: "Kimi K2 Instruct 0905", note: ""),
                CloudModelUI(id: "Pro/moonshotai/Kimi-K2-Instruct-0905", label: "Kimi K2 Instruct 0905 Pro", note: ""),
                CloudModelUI(id: "tencent/Hunyuan-A13B-Instruct", label: "Hunyuan A13B Instruct", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-235B-A22B-Thinking-2507", label: "Qwen3 235B A22B Thinking 2507", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-235B-A22B-Instruct-2507", label: "Qwen3 235B A22B Instruct 2507", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-30B-A3B-Thinking-2507", label: "Qwen3 30B A3B Thinking 2507", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-30B-A3B-Instruct-2507", label: "Qwen3 30B A3B Instruct 2507", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-235B-A22B", label: "Qwen3 235B A22B", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-32B", label: "Qwen3 32B", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-30B-A3B", label: "Qwen3 30B A3B", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-14B", label: "Qwen3 14B", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-8B", label: "Qwen3 8B", note: ""),
                CloudModelUI(id: "THUDM/GLM-Z1-Rumination-32B-0414", label: "GLM-Z1 Rumination 32B 0414", note: ""),
                CloudModelUI(id: "THUDM/GLM-Z1-32B-0414", label: "GLM-Z1 32B 0414", note: ""),
                CloudModelUI(id: "THUDM/GLM-Z1-9B-0414", label: "GLM-Z1 9B 0414", note: ""),
                CloudModelUI(id: "THUDM/GLM-4-32B-0414", label: "GLM-4 32B 0414", note: ""),
                CloudModelUI(id: "THUDM/glm-4-9b-chat", label: "GLM-4 9B Chat", note: ""),
                CloudModelUI(id: "deepseek-ai/DeepSeek-R1", label: "DeepSeek R1", note: ""),
                CloudModelUI(id: "deepseek-ai/DeepSeek-V3", label: "DeepSeek V3", note: ""),
                CloudModelUI(id: "Pro/deepseek-ai/DeepSeek-R1", label: "DeepSeek R1 Pro", note: ""),
                CloudModelUI(id: "Pro/deepseek-ai/DeepSeek-V3", label: "DeepSeek V3 Pro", note: ""),
                CloudModelUI(id: "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B", label: "DeepSeek R1 Distill Qwen 32B", note: ""),
                CloudModelUI(id: "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B", label: "DeepSeek R1 Distill Qwen 14B", note: ""),
                CloudModelUI(id: "Qwen/QwQ-32B", label: "QwQ 32B", note: ""),
                CloudModelUI(id: "Qwen/Qwen2.5-72B-Instruct", label: "Qwen2.5 72B Instruct", note: ""),
                CloudModelUI(id: "Qwen/Qwen2.5-32B-Instruct", label: "Qwen2.5 32B Instruct", note: ""),
                CloudModelUI(id: "Qwen/Qwen2.5-7B-Instruct", label: "Qwen2.5 7B Instruct", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-VL-32B-Instruct", label: "Qwen3 VL 32B Instruct", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-VL-32B-Thinking", label: "Qwen3 VL 32B Thinking", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-Omni-30B-A3B-Instruct", label: "Qwen3 Omni 30B A3B Instruct", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-Omni-30B-A3B-Thinking", label: "Qwen3 Omni 30B A3B Thinking", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-Omni-30B-A3B-Captioner", label: "Qwen3 Omni 30B A3B Captioner", note: ""),
                CloudModelUI(id: "deepseek-ai/DeepSeek-OCR", label: "DeepSeek OCR", note: ""),
                CloudModelUI(id: "zai-org/GLM-4.5V", label: "GLM-4.5V", note: ""),
                CloudModelUI(id: "Qwen/QVQ-72B-Preview", label: "QVQ 72B Preview", note: ""),
                CloudModelUI(id: "Qwen/Qwen2.5-VL-72B-Instruct", label: "Qwen2.5 VL 72B Instruct", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "groq", label: "Groq", mark: "Gq", cls: "groq",
            desc: "Groq", baseURL: "https://api.groq.com/openai/v1", keyHint: "gsk_...", modelLabel: "模型", defaultModel: "meta-llama/llama-4-scout-17b-16e-instruct",
            models: [
                CloudModelUI(id: "groq/compound", label: "Compound", note: ""),
                CloudModelUI(id: "groq/compound-mini", label: "Compound Mini", note: ""),
                CloudModelUI(id: "openai/gpt-oss-120b", label: "GPT OSS 120B", note: ""),
                CloudModelUI(id: "openai/gpt-oss-20b", label: "GPT OSS 20B", note: ""),
                CloudModelUI(id: "moonshotai/kimi-k2-instruct-0905", label: "Kimi K2 0905", note: ""),
                CloudModelUI(id: "meta-llama/llama-4-scout-17b-16e-instruct", label: "Llama 4 Scout (17Bx16E)", note: ""),
                CloudModelUI(id: "meta-llama/llama-4-maverick-17b-128e-instruct", label: "Llama 4 Maverick (17Bx128E)", note: ""),
                CloudModelUI(id: "qwen/qwen3-32b", label: "Qwen3 32B", note: ""),
                CloudModelUI(id: "llama-3.1-8b-instant", label: "Llama 3.1 8B Instant", note: ""),
                CloudModelUI(id: "llama-3.3-70b-versatile", label: "Llama 3.3 70B Versatile", note: ""),
                CloudModelUI(id: "mistral-saba-24b", label: "Mistral Saba 24B", note: ""),
                CloudModelUI(id: "meta-llama/llama-guard-4-12b", label: "Llama Guard 4 12B", note: ""),
                CloudModelUI(id: "meta-llama/llama-prompt-guard-2-22m", label: "Llama Prompt Guard 2 22M", note: ""),
                CloudModelUI(id: "meta-llama/llama-prompt-guard-2-86m", label: "Llama Prompt Guard 2 86M", note: ""),
                CloudModelUI(id: "openai/gpt-oss-safeguard-20b", label: "Safety GPT OSS 20B", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "xai", label: "xAI", mark: "x", cls: "xai",
            desc: "xAI", baseURL: "https://api.x.ai/v1", keyHint: "xai-...", modelLabel: "模型", defaultModel: "grok-4.3",
            models: [
                CloudModelUI(id: "grok-4.3", label: "Grok 4.3", note: ""),
                CloudModelUI(id: "grok-4.20-reasoning", label: "Grok 4.20 Reasoning", note: ""),
                CloudModelUI(id: "grok-4.20-multi-agent", label: "Grok 4.20 Multi-Agent", note: ""),
                CloudModelUI(id: "grok-4-1-fast-reasoning", label: "Grok 4.1 Fast Reasoning", note: ""),
                CloudModelUI(id: "grok-4-1-fast-non-reasoning", label: "Grok 4.1 Fast Non-Reasoning", note: ""),
                CloudModelUI(id: "grok-4-fast-reasoning", label: "Grok 4 Fast Reasoning", note: ""),
                CloudModelUI(id: "grok-4-fast-non-reasoning", label: "Grok 4 Fast Non-Reasoning", note: ""),
                CloudModelUI(id: "grok-code-fast-1", label: "Grok Code Fast 1", note: ""),
                CloudModelUI(id: "grok-4", label: "Grok 4", note: ""),
                CloudModelUI(id: "grok-3", label: "Grok 3", note: ""),
                CloudModelUI(id: "grok-3-mini", label: "Grok 3 Mini", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "mistralai", label: "Mistral AI", mark: "Mi", cls: "mistralai",
            desc: "Mistral AI", baseURL: "https://api.mistral.ai/v1", keyHint: "Your Mistral AI API key", modelLabel: "模型", defaultModel: "mistral-small-latest",
            models: [
                CloudModelUI(id: "mistral-small-latest", label: "Mistral Small Latest", note: ""),
                CloudModelUI(id: "mistral-small-2603", label: "Mistral Small 4 (26.03)", note: ""),
                CloudModelUI(id: "mistral-large-latest", label: "Mistral Large Latest", note: ""),
                CloudModelUI(id: "mistral-large-2512", label: "Mistral Large 3 (25.12)", note: ""),
                CloudModelUI(id: "mistral-medium-latest", label: "Mistral Medium 3.5 Latest", note: ""),
                CloudModelUI(id: "mistral-medium-2508", label: "Mistral Medium 3.1 (25.08)", note: ""),
                CloudModelUI(id: "magistral-medium-latest", label: "Magistral Medium Latest", note: ""),
                CloudModelUI(id: "magistral-medium-2509", label: "Magistral Medium 1.2 (25.09)", note: ""),
                CloudModelUI(id: "magistral-small-latest", label: "Magistral Small Latest", note: ""),
                CloudModelUI(id: "magistral-small-2509", label: "Magistral Small 1.2 (25.09)", note: ""),
                CloudModelUI(id: "devstral-large-latest", label: "Devstral 2 Latest", note: ""),
                CloudModelUI(id: "devstral-2512", label: "Devstral 2 (25.12)", note: ""),
                CloudModelUI(id: "codestral-latest", label: "Codestral Latest", note: ""),
                CloudModelUI(id: "ministral-14b-latest", label: "Ministral 3 14B Latest", note: ""),
                CloudModelUI(id: "ministral-8b-latest", label: "Ministral 3 8B Latest", note: ""),
                CloudModelUI(id: "ministral-3b-latest", label: "Ministral 3 3B Latest", note: ""),
                CloudModelUI(id: "mistral-nemo", label: "Mistral Nemo", note: ""),
                CloudModelUI(id: "pixtral-large-latest", label: "Pixtral Large", note: ""),
                CloudModelUI(id: "pixtral-12b", label: "Pixtral 12B", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "openrouter", label: "OpenRouter", mark: "OR", cls: "openrouter",
            desc: "OpenRouter", baseURL: "https://openrouter.ai/api/v1", keyHint: "sk-or-...", modelLabel: "模型", defaultModel: "openrouter/auto",
            models: [
                CloudModelUI(id: "openrouter/auto", label: "OpenRouter Auto", note: ""),
                CloudModelUI(id: "openai/gpt-5.5", label: "OpenAI GPT-5.5", note: ""),
                CloudModelUI(id: "openai/gpt-5.4", label: "OpenAI GPT-5.4", note: ""),
                CloudModelUI(id: "openai/gpt-5.4-mini", label: "OpenAI GPT-5.4 mini", note: ""),
                CloudModelUI(id: "anthropic/claude-opus-4.7", label: "Claude Opus 4.7", note: ""),
                CloudModelUI(id: "anthropic/claude-sonnet-4.6", label: "Claude Sonnet 4.6", note: ""),
                CloudModelUI(id: "anthropic/claude-haiku-4.5", label: "Claude Haiku 4.5", note: ""),
                CloudModelUI(id: "google/gemini-3.1-pro-preview", label: "Gemini 3.1 Pro Preview", note: ""),
                CloudModelUI(id: "google/gemini-3.1-flash-lite-preview", label: "Gemini 3.1 Flash-Lite Preview", note: ""),
                CloudModelUI(id: "google/gemini-3-flash-preview", label: "Gemini 3 Flash Preview", note: ""),
                CloudModelUI(id: "deepseek/deepseek-chat-v3.1", label: "DeepSeek Chat V3.1", note: ""),
                CloudModelUI(id: "deepseek/deepseek-r1-0528", label: "DeepSeek R1 0528", note: ""),
                CloudModelUI(id: "qwen/qwen3-235b-a22b", label: "Qwen3 235B A22B", note: ""),
                CloudModelUI(id: "qwen/qwen3-32b", label: "Qwen3 32B", note: ""),
                CloudModelUI(id: "meta-llama/llama-3.3-70b-instruct", label: "Llama 3.3 70B Instruct", note: ""),
                CloudModelUI(id: "mistralai/mistral-large", label: "Mistral Large", note: ""),
                CloudModelUI(id: "google/gemini-2.5-flash-image-preview", label: "Gemini 2.5 Flash Image Preview", note: ""),
                CloudModelUI(id: "meta-llama/llama-3.2-11b-vision-instruct", label: "Llama 3.2 11B Vision Instruct", note: ""),
                CloudModelUI(id: "meta-llama/llama-3.2-90b-vision-instruct", label: "Llama 3.2 90B Vision Instruct", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "together", label: "Together AI", mark: "Tg", cls: "together",
            desc: "Together AI", baseURL: "https://api.together.xyz/v1", keyHint: "Enter your Together AI API key", modelLabel: "模型", defaultModel: "MiniMaxAI/MiniMax-M2.7",
            models: [
                CloudModelUI(id: "MiniMaxAI/MiniMax-M2.7", label: "MiniMax M2.7", note: ""),
                CloudModelUI(id: "MiniMaxAI/MiniMax-M2.5", label: "MiniMax M2.5", note: ""),
                CloudModelUI(id: "Qwen/Qwen3.5-397B-A17B", label: "Qwen3.5 397B A17B", note: ""),
                CloudModelUI(id: "Qwen/Qwen3.5-9B", label: "Qwen3.5 9B", note: ""),
                CloudModelUI(id: "zai-org/GLM-5.1", label: "GLM-5.1", note: ""),
                CloudModelUI(id: "zai-org/GLM-5", label: "GLM-5", note: ""),
                CloudModelUI(id: "moonshotai/Kimi-K2.5", label: "Kimi K2.5", note: ""),
                CloudModelUI(id: "moonshotai/Kimi-K2-Thinking", label: "Kimi K2 Thinking", note: ""),
                CloudModelUI(id: "moonshotai/Kimi-K2-Instruct-0905", label: "Kimi K2 Instruct 0905", note: ""),
                CloudModelUI(id: "deepseek-ai/DeepSeek-V3.1", label: "DeepSeek V3.1", note: ""),
                CloudModelUI(id: "deepseek-ai/DeepSeek-R1", label: "DeepSeek R1", note: ""),
                CloudModelUI(id: "openai/gpt-oss-120b", label: "GPT-OSS 120B", note: ""),
                CloudModelUI(id: "openai/gpt-oss-20b", label: "GPT-OSS 20B", note: ""),
                CloudModelUI(id: "zai-org/GLM-4.6", label: "GLM 4.6", note: ""),
                CloudModelUI(id: "zai-org/GLM-4.5-Air-FP8", label: "GLM 4.5 Air FP8", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-235B-A22B-Thinking-2507", label: "Qwen3 235B A22B Thinking 2507", note: ""),
                CloudModelUI(id: "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8", label: "Qwen3 Coder 480B A35B Instruct FP8", note: ""),
                CloudModelUI(id: "meta-llama/Llama-4-Scout-17B-16E-Instruct", label: "Llama 4 Scout Instruct", note: ""),
                CloudModelUI(id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", label: "Llama 4 Maverick Instruct FP8", note: ""),
                CloudModelUI(id: "meta-llama/Llama-3.3-70B-Instruct-Turbo", label: "Llama 3.3 70B Instruct Turbo", note: ""),
                CloudModelUI(id: "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo", label: "Llama 3.1 405B Instruct Turbo", note: ""),
                CloudModelUI(id: "Qwen/Qwen2.5-72B-Instruct-Turbo", label: "Qwen2.5 72B Instruct Turbo", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "ollama", label: "Ollama", mark: "Ol", cls: "ollama",
            desc: "Ollama", baseURL: "http://127.0.0.1:11434", keyHint: "API Key", modelLabel: "模型", defaultModel: "llama3.1",
            models: [
                CloudModelUI(id: "deepseek-v3.1:671b", label: "DeepSeek V3.1", note: ""),
                CloudModelUI(id: "gpt-oss:20b", label: "GPT-OSS 20B", note: ""),
                CloudModelUI(id: "gpt-oss:120b", label: "GPT-OSS 120B", note: ""),
                CloudModelUI(id: "qwen3-coder:480b", label: "Qwen3 Coder 480B", note: ""),
                CloudModelUI(id: "deepseek-r1", label: "DeepSeek R1", note: ""),
                CloudModelUI(id: "deepseek-v3", label: "DeepSeek V3 671B", note: ""),
                CloudModelUI(id: "llama3.1", label: "Llama 3.1 8B", note: ""),
                CloudModelUI(id: "llama3.1:70b", label: "Llama 3.1 70B", note: ""),
                CloudModelUI(id: "llama3.1:405b", label: "Llama 3.1 405B", note: ""),
                CloudModelUI(id: "codellama", label: "Code Llama 7B", note: ""),
                CloudModelUI(id: "codellama:13b", label: "Code Llama 13B", note: ""),
                CloudModelUI(id: "codellama:34b", label: "Code Llama 34B", note: ""),
                CloudModelUI(id: "codellama:70b", label: "Code Llama 70B", note: ""),
                CloudModelUI(id: "qwq", label: "QwQ 32B", note: ""),
                CloudModelUI(id: "qwen3", label: "Qwen3 7B", note: ""),
                CloudModelUI(id: "qwen2.5:0.5b", label: "Qwen2.5 0.5B", note: ""),
                CloudModelUI(id: "qwen2.5:1.5b", label: "Qwen2.5 1.5B", note: ""),
                CloudModelUI(id: "qwen2.5", label: "Qwen2.5 7B", note: ""),
                CloudModelUI(id: "qwen2.5:72b", label: "Qwen2.5 72B", note: ""),
                CloudModelUI(id: "gemma2:2b", label: "Gemma 2 2B", note: ""),
                CloudModelUI(id: "gemma2", label: "Gemma 2 9B", note: ""),
                CloudModelUI(id: "gemma2:27b", label: "Gemma 2 27B", note: ""),
                CloudModelUI(id: "mistral", label: "Mistral 7B", note: ""),
                CloudModelUI(id: "mixtral", label: "Mixtral 8x7B", note: ""),
                CloudModelUI(id: "mixtral:8x22b", label: "Mixtral 8x22B", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
        CloudProviderUI(
            key: "lmstudio", label: "LM Studio", mark: "LM", cls: "lmstudio",
            desc: "LM Studio", baseURL: "http://127.0.0.1:1234/v1", keyHint: "API Key", modelLabel: "模型", defaultModel: "lmstudio-local",
            models: [
                CloudModelUI(id: "lmstudio-local", label: "LM Studio (Local)", note: ""),
            ],
            price: "按 token 计费(以所选服务商为准)"),
    ]
}
